### ISSUE TITLE
Existing package not found

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm#3132] opened 2024-05-28 13:54 UTC
### Describe the bug
Existing package not found
### To reproduce
```
$ sudo rpm -vv -i rubygem-bundler
D: ============== rubygem-bundler
error: open of rubygem-bundler failed: No such file or directory
D: found 0 source and 0 binary packages
D: Exit status: 1
```
### Expected behaviour
Proceed to install existing package
```
$ dnf -q list rubygem-bundler
Available Packages
rubygem-bundler.noarch          2.5.9-7.fc40           updates
```
### Environment
 - OS / distribution: Fedora 40
 - RPM version: 4.19.1.1

**Comment by ffesti** [comment] 2024-06-01 12:31
Yeah, `rpm -i` needs file name as an argument. `rubygem-bundler` is a package name but not a typical rpm package file name. Do you try to use an installer like `dnf` which would download the newest version of the package for you?

Anyway. This is not a bug but expected behaviour. Closing.

**Closed by ffesti** 2024-06-01 12:31 UTC
