### ISSUE TITLE
regression: specifying "%_gpg_name First Last <email@fool.com>" does not work

### ISSUE THREAD

**Issue by dustymabe** [rpm-software-management/rpm#120] opened 2017-01-09 17:05 UTC
In the example shown [here](https://github.com/rpm-software-management/rpm/blob/1ce844ab263bf49ee6d5145ed09e73f2c17924cc/doc/rpmsign.8#L67) I should be able to specify a macro of `%_gpg_name Dusty Mabe <dusty@dustymabe.com>` and be able to use that. Unfortunately, i get this error instead: 

```
$ rpm --addsign ./grub2-2.02-0.38.fc25.dusty.x86_64.rpm                           
./grub2-2.02-0.38.fc25.dusty.x86_64.rpm:
gpg: signing failed: Line passed to IPC too long
gpg: signing failed: Line passed to IPC too long
error: gpg exec failed (2)
```

I don't think this is a doc bug because I see other examples around the internet where this format is used. One of them is [here](https://blog.packagecloud.io/eng/2014/11/24/howto-gpg-sign-verify-rpm-packages-yum-repositories/) where the person uses `%_gpg_name Alicia Gonzalez <agonzalez@packagecloud.io>`. So it looks like a regression where this used to work. 

Note that if I use `Dusty Mabe` or `dusty@dustymabe.com` it works fine. So it looks like the "handoff" to gpg might just need some fixing up?

**Comment by pmatilai** [comment] 2017-01-11 09:55
That's strange. I'm not able to reproduce that, and it doesn't seem to be about actual length either since my name is longer and I always had this in my ~/.rpmmacros:
`%_gpg_name Panu Matilainen <pmatilai@redhat.com>`

What version of rpm, gpg and what distro are you using?

**Comment by pmatilai** [comment] 2017-01-11 10:27
Okay, this is actually a bug in pinentry, see https://bugs.gnupg.org/gnupg/issue2452
With that info I can also reproduce the behavior by forcing an empty environment:
```
error: gpg exec failed (2)
[pmatilai@sopuli rpm]$ cp ~/Downloads/xfce4-terminal-0.8.2-2.fc25.x86_64.rpm /tmp/; env -i HOME=/home/pmatilai ./rpmsign --addsign /tmp/xfce4-terminal-0.8.2-2.fc25.x86_64.rpm
/tmp/xfce4-terminal-0.8.2-2.fc25.x86_64.rpm:
gpg: signing failed: Line passed to IPC too long
gpg: signing failed: Line passed to IPC too long
error: gpg exec failed (2)
[pmatilai@sopuli rpm]$
```

The error occurs if neither DISPLAY or TERM is set in the environment.

**Comment by pmatilai** [comment] 2017-01-11 10:38
OTOH the pinentry bug doesn't explain behavior change with different %_gpg_name value. Can you reproduce the problem if you explicity set TERM to something, eg

`TERM=xterm rpm --addsign ./grub2-2.02-0.38.fc25.dusty.x86_64.rpm`

**Comment by dustymabe** [comment] 2017-01-11 14:23
hey @pmatilai - i'm using fedora 24 with:
```
$ rpm -q rpm rpm-sign gnupg2 gnupg 
rpm-4.13.0-1.fc24.x86_64
rpm-sign-4.13.0-1.fc24.x86_64
gnupg2-2.1.13-2.fc24.x86_64
gnupg-1.4.21-1.fc24.x86_64
```

my DISPLAY variable is unset but my `TERM` is `screen-256color`. What is odd that I am trying to reproduce today in the very same terminal that I was having the problem in the other day (I can see the output in the scrollback) and the "in terminal" text based popup is now coming up and asking me for my password. I'm not sure what the problem is/was.

**Comment by pmatilai** [comment] 2017-02-01 09:32
Okay, lets assume it was related to those environment variables since you're seeing it now. Like said, the "IPC line too long" is actually a bug in pinentry not rpm so closing this one.

Feel free to reopen if you can reproduce in a way that points it back to rpm.

**Closed by pmatilai** 2017-02-01 09:32 UTC

**Comment by dustymabe** [comment] 2017-02-01 13:20
Agreed, I'll let you know if I see the problem again. Thanks
