### ISSUE TITLE
Odd handing of URLs containing a ? in Source*:/Patch*: lines

### ISSUE THREAD

**Issue by berolinux** [rpm-software-management/rpm#1407] opened 2020-10-21 12:24 UTC
When using an URL containing a ? in Source*:/Patch*: lines, the file name assumed by rpm is truncated to the bits after the ?, not not the filename preceding it.
This makes it hard to e.g. reference a patch being "stolen" from Arch Linux since e.g.
Patch1: https://aur.archlinux.org/cgit/aur.git/plain/chromium-skia-harmony.patch?h=chromium-vaapi
Patch2: https://aur.archlinux.org/cgit/aur.git/plain/fix-invalid-end-iterator-usage-in-CookieMonster.patch?h=chromium-vaapi
results in references to 2 files called "chromium-vaapi", when any regular parsing of the URL would expect it to become chromium-skia-harmony.patch and fix-invalid-end-iterator-usage-in-CookieMonster.patch

**Comment by Conan-Kudo** [comment] 2020-11-01 17:51
I would actually expect it to be `chromium-skia-harmony.patch?h=chromium-vaapi` or `fix-invalid-end-iterator-usage-in-CookieMonster.patch?h=chromium-vaapi` instead, since the idea is that the filenames are determined by the last path separator (I believe that's what `basename` does...).

**Comment by berolinux** [comment] 2020-11-01 17:56
I would expect it to be chromium-skia-harmony.patch or fix-invalid-end-iterator-usage-in-CookieMonster.patch because that's what you get if you use wget or curl on the same URLs, given the ? is usually a separator between address and parameters.
But either of those would be fine with me, while just calling both chromium-vaapi is problematic.

**Comment by dmnks** [comment] 2021-03-02 16:36
This is a known limitation in RPM, but there's a simple workaround, see below.

The way RPM [derives](https://github.com/rpm-software-management/rpm/blob/d601a7b7ae764b31ad74b2dceff1eafb5297147f/build/parsePreamble.c#L125) the target file name from a Patch/Source tag is by taking everything after the last `/` or `=` character, whichever comes last. That means, you can use a trick that involves appending a dummy URL fragment (`#/`) to force RPM to name the file differently, as follows:

```
Patch1: https://aur.archlinux.org/cgit/aur.git/plain/chromium-skia-harmony.patch?h=chromium-vaapi#/chromium-skia-harmony.patch
```

This is also documented in the Fedora wiki: https://fedoraproject.org/wiki/Packaging:SourceURL#Troublesome_URLs

The downside of this workaround is that you may need to repeat the original name of the file (unless you choose a different, perhaps shorter name), which makes the URL more verbose and more prone to error.

Now, as per [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.3), what follows after the `?` (query component) is not considered part of the *path*, so I agree it would make sense for RPM to strip that. However, if we made such a change now, I worry that some existing spec(s) out there would break, due to the assumption that `=` also acts as a file name separator:

```
Patch1: https://some/url/getpatch?name=foobar
```

This would store the file as `getpatch` as opposed to the previous `foobar`.

I wasn't able to trace down the exact rationale behind the `=` char in the spec parser, but I assume the idea was to allow such renames, similarly to `#/`.

For some real-world data, I grepped [all the ~21k Fedora spec files](https://pkgs.fedoraproject.org/repo/rpm-specs-latest.tar.xz) and although there were quite a few that had a query component in one of the Patch/Source tags, I didn't find a single one that would rely on the `=` separator alone (there always was a `/` used to separate the target file name).

Still, we'd rather not introduce more "magic" to the URL parsing logic and risk a regression along the way, so I'll close this one. I'm hoping the URL fragment workaround will be sufficient for your use case! :)

**Closed by dmnks** 2021-03-02 16:36 UTC
