### ISSUE TITLE
The installation of the FIFO file is blocked.

### ISSUE THREAD

**Issue by JetXujing** [rpm-software-management/rpm#2252] opened 2022-11-01 07:34 UTC
1. rpmbuild -ba test-fsmMkfifo.spec
```
[root@localhost SPECS]# cat test-fsmMkfifo.spec
Name: hello
Version: 1.0
Release: 1
Group: Testing
License: GPL
Summary: Simple rpm demonstration.
Source0: hello-1.0.tar.gz

%description
Simple rpm demonstration.

%prep

%build

%install
mkfifo %{buildroot}/test-fifo

%files
/test-fifo
```
2. rpm -ivh /root/rpmbuild/RPMS/aarch64/hello-1.0-1.aarch64.rpm
![image](https://user-images.githubusercontent.com/43668249/199181757-d647ca64-ea62-4f40-b7f3-dca6d0e69312.png)

The problem can be reproduced according to the preceding steps.
The stack is as follows:
```
(gdb) bt
#0  0x0000ffff9f9a74f4 in __libc_openat64 (fd=fd@entry=11, file=file@entry=0xaaaafa6fa8a0 "/test-fifo;6360cb13", oflag=oflag@entry=33024)
    at ../sysdeps/unix/sysv/linux/openat64.c:45
#1  0x0000ffff9f9a746c in __openat_2 (fd=fd@entry=11, file=file@entry=0xaaaafa6fa8a0 "/test-fifo;6360cb13", oflag=oflag@entry=33024)
    at openat_2.c:28
#2  0x0000ffffa011512c in openat (__oflag=33024, __path=0xaaaafa6fa8a0 "/test-fifo;6360cb13", __fd=11) at /usr/include/bits/fcntl2.h:133
#3  fsmOpenat (dirfd=11, path=0xaaaafa6fa8a0 "/test-fifo;6360cb13", flags=256) at fsm.c:420
#4  0x0000ffffa0117514 in rpmPackageFilesInstall (ts=<optimized out>, te=<optimized out>, files=<optimized out>, psm=psm@entry=0xaaaafa621f60,
    failedFile=failedFile@entry=0xfffff71bf0f0) at fsm.c:1140
#5  0x0000ffffa011df0c in rpmpsmUnpack (psm=psm@entry=0xaaaafa621f60) at psm.c:595
#6  0x0000ffffa011ef04 in rpmPackageInstall (psm=0xaaaafa621f60, ts=0xaaaafa5e81a0) at psm.c:676
#7  runGoal (goal=PKG_INSTALL, psm=0xaaaafa621f60) at psm.c:843
#8  rpmpsmRun (ts=0xaaaafa5e81a0, te=te@entry=0xaaaafa61caa0, goal=PKG_INSTALL) at psm.c:884
#9  0x0000ffffa014765c in rpmteProcess (te=te@entry=0xaaaafa61caa0, goal=<optimized out>, num=num@entry=0) at rpmte.c:817
#10 0x0000ffffa01530c4 in rpmtsProcess (ts=0xaaaafa5e81a0) at transaction.c:1628
#11 rpmtsRun (ts=ts@entry=0xaaaafa5e81a0, okProbs=okProbs@entry=0x0, ignoreSet=<optimized out>) at transaction.c:1842
#12 0x0000ffffa013be70 in rpmcliTransaction (ts=ts@entry=0xaaaafa5e81a0, ia=ia@entry=0xffffa01d7868 <rpmIArgs>, numPackages=1)
    at rpminstall.c:291
#13 0x0000ffffa013de4c in rpmInstall (ts=0xaaaafa5e81a0, ia=0xffffa01d7868 <rpmIArgs>, fileArgv=<optimized out>) at rpminstall.c:633
#14 0x0000aaaadf362ce8 in main (argc=3, argv=<optimized out>) at rpm.c:265
```

I think the reason is that the fifo file is opened in blocking mode. Is this reasonable? Should non-blocking be used?

**Comment by pmatilai** [comment] 2022-11-01 07:39
This is a duplicate of #2195, but thanks for the reproducer!

**Closed by pmatilai** 2022-11-01 07:39 UTC
