### ISSUE TITLE
Disable SHA1, MD5, RIPEMD160, and <2048 bit RSA/DSA in signatures and signed hashes

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1467] opened 2020-12-26 04:17 UTC
Hash functions with outputs smaller than 224 bits, and <2048 bit RSA and DSA signatures, are not a good idea.  RPM should refuse to rely on such algorithms for security.

**Comment by Conan-Kudo** [comment] 2020-12-26 08:39
We probably would want this as a knob, because users can't help it if an RPM uses those hash functions and they need to install it. Admittedly, I think we've been using SHA256 digests since RPM 4.11 (RHEL7), but Enterprise Linux distributions live a _long_ time. Defaulting to those being turned off (and hard-disable in FIPS mode) probably makes sense, though.

**Comment by DemiMarie** [comment] 2020-12-26 17:40
A knob that defaults to off would be fine.

**Comment by pmatilai** [comment] 2021-01-05 09:40
Those ancient hashes, SIGMD5 in particular, are a mandatory part of the rpm package format as documented in LSB. Rpm >= 4.14.2 has the necessary technology to finally make the MD5 header+payload hash properly obsolete, but that's a very, very new development in terms of rpm time.

A thing like this is a policy decision, and we try to avoid those in rpm.

**Comment by DemiMarie** [comment] 2021-01-05 21:45
To clarify: this bug only applies to signatures and signed hashes.  Hashes in the signature area, such as SIGMD5, are not security sensitive.

**Comment by pmatilai** [comment] 2021-01-22 14:34
For all practical purposes, this is a dupe of #1292, closing. 
The first opportunity to *drop* anything is rpm v6 whenever that comes, until then we can only make sure rpm doesn't *depend* on obsolete crypto. As of rpm >= 4.14 it no longer does.

**Closed by pmatilai** 2021-01-22 14:34 UTC

**Comment by DemiMarie** [comment] 2021-01-22 14:55
@pmatilai is it *possible* to disable those via configuration?  That should be doable before RPMv6.  I would certainly like to disable them locally.
