### ISSUE TITLE
Supporting %patch -T option

### ISSUE THREAD

**Issue by junaruga** [rpm-software-management/rpm#788] opened 2019-07-10 16:27 UTC
I wanted to use `patch -T` option for %patch macro, to set fixed timestamp for a patched file.

Because It is related to reproductive build. The timestamp is used as a gz file's metadata modified date in a program.

Is it possible to support the option?

ruby.spec

```
-%patch20 -p1
+%patch20 -p1 -T
```

```
$ rhpkg srpm
error: unknown option: -T: %patch20 -p1 -T


error: unknown option: -T: %patch20 -p1 -T

Could not execute srpm: Failed to execute command.
```

https://github.com/rpm-software-management/rpm/blob/master/build/parsePrep.c#L403-L413

```
static rpmRC doPatchMacro(rpmSpec spec, const char *line)
{
...
    struct poptOption const patchOpts[] = {
	{ NULL, 'P', POPT_ARG_STRING, &opt_P, 'P', NULL, NULL },
	{ NULL, 'p', POPT_ARG_INT, &opt_p, 'p', NULL, NULL },
	{ NULL, 'R', POPT_ARG_NONE, &opt_R, 'R', NULL, NULL },
	{ NULL, 'E', POPT_ARG_NONE, &opt_E, 'E', NULL, NULL },
	{ NULL, 'b', POPT_ARG_STRING, &opt_b, 'b', NULL, NULL },
	{ NULL, 'z', POPT_ARG_STRING, &opt_b, 'z', NULL, NULL },
	{ NULL, 'F', POPT_ARG_INT, &opt_F, 'F', NULL, NULL },
	{ NULL, 'd', POPT_ARG_STRING, &opt_d, 'd', NULL, NULL },
	{ NULL, 'o', POPT_ARG_STRING, &opt_o, 'o', NULL, NULL },
	{ NULL, 0, 0, NULL, 0, NULL, NULL }
    };
...
```

**Comment by junaruga** [comment] 2019-07-11 09:18
Or I want an option for %patch to preserve the timestamp of the patched file like `cp -p`.

**Comment by ffesti** [comment] 2019-07-11 11:02
I wonder if using -Z is the better option when it comes to reproducibility.

**Comment by junaruga** [comment] 2019-07-11 14:38
It seems `-Z` is better than `-T`.

```
$ man patch
...
       -T  or  --set-time
          Set  the modification and access times of patched files from time stamps given in
          context diff headers.  Unless specified in the time stamps, assume that the  con‐
          text diff headers use local time.

          Use  of this option with time stamps that do not include time zones is not recom‐
          mended, because patches using local time cannot easily be used by people in other
          time  zones,  and  because local time stamps are ambiguous when local clocks move
          backwards during daylight-saving time adjustments.  Make sure  that  time  stamps
          include  time  zones,  or  generate  patches with UTC and use the -Z or --set-utc
          option instead.
...
```

**Comment by ffesti** [comment] 2019-07-12 07:57
The other question is whether this should be added to _default_patch_flags in the long run. So instead of packager adding it all over the place it can be enabled globally. Probably in some distribution first before changing the upstream default.

**Comment by junaruga** [comment] 2019-07-12 09:29
> The other question is whether this should be added to _default_patch_flags in the long run.

This is the best solution for me if we can add it to the _default_patch_flags.

**Comment by junaruga** [comment] 2019-07-12 15:09
I tested `patch -Z` on my local using this repository's README file.

I created below 2 files based on a result of `diff -u`.
I expected the patched file is updated as fixed value.
But actually on below cases, it is updated as system date even when using `patch -Z`.
Just implementing `patch -Z` option is not enough.
Because I always want to see the patched file is updated as fixed date when using the option.

```
$ rpm -q patch
patch-2.7.6-9.fc30.x86_64

$ patch -v | head -1
GNU patch 2.7.6
```


## diff file with date header

```
$ cat readme.diff 
--- a/README	2019-07-11 16:33:14.340372704 +0200
+++ b/README	2019-07-12 16:00:00.684469239 +0200
@@ -1,3 +1,4 @@
+aaa
 This is RPM, the RPM Package Manager.
 
 The latest releases are always available at:
```

```
$ touch -d 20190101 README 

$ ls -l README 
-rw-rw-r-- 1 jaruga jaruga 603 Jan  1  2019 README

$ patch -p1 -Z < readme.diff 
patching file README
Not setting time of file README (time mismatch)

$ ls -l README 
-rw-rw-r-- 1 jaruga jaruga 607 Jul 12 16:58 README
```

`README` is updated as system date (Jul 12 16:58).

"Not setting time of file README (time mismatch)" message is here.
https://github.com/mirror/patch/blob/v2.7.6/src/patch.c#L581-L583

## diff file without date header

```
$ cat readme2.diff 
--- a/README
+++ b/README
@@ -1,3 +1,4 @@
+aaa
 This is RPM, the RPM Package Manager.
 
 The latest releases are always available at:
```

```
$ touch -d 20190101 README 

$ ls -l README 
-rw-rw-r-- 1 jaruga jaruga 603 Jan  1  2019 README

$ patch -p1 -Z < readme2.diff 
patching file README

$ ls -l README 
-rw-rw-r-- 1 jaruga jaruga 607 Jul 12 17:03 README
```

`README` is updated as system date (Jul 12 17:03).

**Comment by pavlinamv** [comment] 2019-07-12 19:25
_The --set-utc (-Z) option causes patch to set a patched file’s modification and access times to the timestamps given in context diff headers._ 
=>
behavior of diff file without date header 

_patch normally refrains from setting a file’s timestamps if the file’s original last-modified timestamp does not match the time given in the diff header, of if the file’s contents do not exactly match the patch._
=>
behavior of diff file with date header

See https://www.gnu.org/software/diffutils/manual/html_node/Patching-Timestamps.html#Patching-Timestamps

**Comment by junaruga** [comment] 2019-07-13 13:19
Thanks for the info. I understand it.
I simply like the behavior like `cp -p` just to preserve the timestamp.
Because it always update the file as fixed date.

**Comment by ffesti** [comment] 2020-01-31 13:33
Looks like neither patch -T nor -Z really does what's wanted here. As there haven't been any other suggestions for half a year I am closing this for now. Feel free to re-open if there are better options emerging.

**Closed by ffesti** 2020-01-31 13:33 UTC
