### ISSUE TITLE
%autosetup does not handle multiple -a<num>

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#725] opened 2019-06-02 09:15 UTC
Looks like if multiple -a<num>  are specified as %autosetup parameters none of the additional archive are unpacked.
Workaround is use:
```
%setup -q -a<num1> -a<num2>
%autopatch
```

**Comment by ignatenkobrain** [comment] 2019-06-02 09:16
This is a duplicate of 462

**Closed by ignatenkobrain** 2019-06-02 09:16 UTC
