### ISSUE TITLE
Bogus warning about files listed twice

### ISSUE THREAD

**Issue by thmo** [rpm-software-management/rpm#2334] opened 2022-12-31 11:21 UTC
For this minimal spec file
```
Version: 0
Release: 0
Name: dummy
License: dummy
Summary: dummy
%description
dummy
%prep
mkdir -p foo1/bar foo2/bar
touch foo1/bar/a foo2/bar/b
%files
%doc foo1/bar
%doc foo2/bar
```
`rpmbuild` emits this warning:
```
    File listed twice: /usr/share/doc/dummy/bar
    File listed twice: /usr/share/doc/dummy/bar/a
    File listed twice: /usr/share/doc/dummy/bar/b
```
This is misleading, as from a spec file perspective, no file is listed twice. Effectively the two `bar` directories are merged, which might or might not be intended by the spec file author. For a larger spec file it can be hard to find the real cause of the warning.

Might be related to #336. Not sure whether the proposed fix there will fix this one here as well.

**Comment by pmatilai** [comment] 2023-09-14 05:47
This is a dupe of #336, closing.

**Closed by pmatilai** 2023-09-14 05:47 UTC
Labels: bug, duplicate
