### ISSUE TITLE
RFE: implement fast mode for getting EVR

### ISSUE THREAD

**Issue by ignatenkobrain** [rpm-software-management/rpm#392] opened 2018-02-10 08:08 UTC
rpmspec is quite slow because it needs to parse whole spec and so on. Would be nice if there would be some flag to turn off `%include`, parsing of all sections and just give me stupid EVR. It won't check spec for correctness and such, but it would be very fast.

Just to give some background, I'm writing tool which is generating RPM changelogs out of git history and rpmspec is slowest part in there.

**Comment by n3npq** [comment] 2018-02-16 23:29
Um, spec file parsing is not exactly slow (even with lightly used %include) and there already is a means to query EVR from a spec file.

Presumably you are seeking the EVR used on every %changelog entry by brute force: try being more clever, by (say) pickling a store in the git directory incrementally.

**Comment by ignatenkobrain** [comment] 2018-02-17 10:26
@n3npq believe me, it is slowest part in my tool ;)

```
287.25user 152.95system 2:11.94elapsed 333%CPU (0avgtext+0avgdata 68724maxresident)k
13648inputs+0outputs (53major+30349595minor)pagefaults 0swaps
```

```diff
diff --git a/src/main.rs b/src/main.rs
index 4b0f2ff..9306517 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -79,6 +79,7 @@ fn run(opt: &Opt) -> Result<(), Error> {
             let atime = author.when();
             let datetime =
                 FixedOffset::east(atime.offset_minutes() * 3600 / 60).timestamp(atime.seconds(), 0);
+            /*
             let output = Command::new("rpmspec")
                 .args(&[
                     "--srpm",
@@ -92,6 +93,7 @@ fn run(opt: &Opt) -> Result<(), Error> {
                     workdir.join(&spec).to_str().unwrap(),
                 ])
                 .output()?;
+            */
 
             let mut chlog_header = format!(
                 "* {} {} <{}>",
@@ -99,11 +101,13 @@ fn run(opt: &Opt) -> Result<(), Error> {
                 author.name().unwrap_or("Nobody"),
                 author.email().unwrap_or("nobody@fedoraproject.org"),
             );
+            /*
             if output.status.success() {
                 chlog_header.push_str(&format!(" - {}", String::from_utf8_lossy(&output.stdout)));
             } else {
                 eprintln!("{}", String::from_utf8_lossy(&output.stderr));
             }
+            */
             let chlog_entry = format!("- {}", commit.summary().unwrap());
 
             Ok(Some(format!("{}\n{}", chlog_header, chlog_entry)))
```

```
13.41user 2.05system 0:03.20elapsed 482%CPU (0avgtext+0avgdata 66184maxresident)k
0inputs+0outputs (0major+495394minor)pagefaults 0swaps
```

**Comment by n3npq** [comment] 2018-02-17 12:07
Um, that snippet of code reveals too little to understand anything. 

Still: I am very surprised if any *single* spec file parse takes more than *two minutes* to parse and retrieve EVR information.

**Comment by n3npq** [comment] 2018-02-17 12:52
Ok. So the issue isn't that rpmspec is particularly slow, just that you are running thousands of queries.

Since your program appears to be multithreaded, try splitting the 4000 specfile queries across 10-20 worker threads.

**Comment by ignatenkobrain** [comment] 2018-02-17 12:57
> Since your program appears to be multithreaded, try splitting the 4000 specfile queries across 10-20 worker threads.

That's exactly what it does.

**Comment by ignatenkobrain** [comment] 2018-02-17 12:57
If I would be querying them sequentially, then it would take hour or so

**Comment by n3npq** [comment] 2018-02-17 13:04
Then you are stuck: it's your workload, not the rpmspec parser implementation, that is the root cause.

**Comment by ffesti** [comment] 2018-03-12 12:28
yup, wontfix.

**Closed by ffesti** 2018-03-12 12:28 UTC
