### ISSUE TITLE
rpm-4.18.0 embeds build machine CPU count

### ISSUE THREAD

**Issue by bmwiedemann** [rpm-software-management/rpm#2343] opened 2023-01-10 07:17 UTC
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that the recent upgrade to rpm-4.18.0  
with #2047 / #1241 caused spec files with

```bash
make %{?_smp_mflags}
```

to embed the build machine CPU count into .src.rpm files, making them hard to bit-reproduce.
binary rpm files embed the .src.rpm header checksum, so suffer as well.

It might also introduce other hard-to-reproduce details, but I have not looked for these, yet.

**Comment by pmatilai** [comment] 2023-01-10 08:58
Right. This is very similar to the LTO case (7faf8eda1358f8a877b9b3d6e1197b814e80b50b), with probably a similar solution. The simple and sane solution is to have _smp_mflags expand to `-j${RPM_BUILD_NCPUS}` 

Which ... we already did for slightly different reasons, but apparently I completely forgot about it in the meanwhile :laughing:  - see 0576d24756fe975d890f5535a21cfdfd35fc2ca4. We just need to  backport it to 4.18.

**Comment by bmwiedemann** [comment] 2023-01-10 21:38
I tried

```diff
===================================================================
--- rpm-4.18.0.orig/platform.in
+++ rpm-4.18.0/platform.in
@@ -57,7 +57,7 @@
         if [ -n "$ncpus_max" ] && [ "$ncpus_max" -gt 0 ] && [ "$RPM_BUILD_NCPUS" -gt "$ncpus_max" ]; then RPM_BUILD_NCPUS="$ncpus_max"; fi; \\\
         echo "$RPM_BUILD_NCPUS";)
 
-%_smp_mflags -j%{_smp_build_ncpus}
+%_smp_mflags -j${RPM_BUILD_NCPUS}
 
 # Maximum number of threads to use when building, 0 for unlimited
 #%_smp_nthreads_max 0
```

But somehow I still get this diff
```diff
-make -j4
+make -j1
```

the produced  `/usr/lib/rpm/platform/x86_64-linux/macros` has
```
%_smp_mflags -j%{_RPM_BUILD_NCPUS}
```

Why is that?

**Comment by bmwiedemann** [comment] 2023-01-11 03:42
I checked git log and found some related commits.
#2344 now does the trick for me.

**Comment by pmatilai** [comment] 2023-01-11 09:57
As mentioned in the PR,  `-j${_RPM_BUILD_NCPUS}` cannot possibly expand to -j<number> because the macro engine does not expand environment variables from by `$`. You appear to have a redefinition of %_smp_mflags someplace, ~/.rpmmacros being one of the possibilities.

**Comment by bmwiedemann** [comment] 2023-01-11 10:05
Right something writes it into ~/.rpmmacros . That is our problem then and the `-j%{_RPM_BUILD_NCPUS}
` rpm patch should still be good.

**Comment by pmatilai** [comment] 2023-01-11 10:13
> `-j%{_RPM_BUILD_NCPUS}` rpm patch should still be good.

Note, it's `-j${_RPM_BUILD_NCPUS}`, not with `%`

**Comment by bmwiedemann** [comment] 2023-01-11 10:35
I have it with `-j${RPM_BUILD_NCPUS}` in https://build.opensuse.org/package/view_file/home:bmwiedemann:reproducible/rpm/0576d24756f.patch , but somehow it gets replaced by `%_smp_mflags -j%{_RPM_BUILD_NCPUS}` in platform files, which then breaks because the macro is unknown.
With the move to `macros.in`, it works. Is there some special rewriting?

**Comment by pmatilai** [comment] 2023-01-11 10:50
Oh. That's installplatform being over-eager (`-e '/\${\w*:-/!s,\${,%{_,' ` presumably). So better to include the move to macros then, it's the right thing anyhow.

**Comment by pmatilai** [comment] 2023-01-11 11:26
To whomever ends up doing 4.18.1 release: this needs commits 5049fc701561b258b722b3400460d8828ce9e64e and 0576d24756fe975d890f5535a21cfdfd35fc2ca4

**Comment by Conan-Kudo** [comment] 2023-01-11 16:26
> Right something writes it into ~/.rpmmacros . That is our problem then and the `-j%{_RPM_BUILD_NCPUS} ` rpm patch should still be good.

This is probably `obs-build`, which redefines a bunch of stuff in `~/.rpmmacros` when it shouldn't.

**Comment by bmwiedemann** [comment] 2023-01-11 16:28
Yes. It came from https://github.com/openSUSE/obs-build/blob/master/build-recipe#L234

**Comment by bmwiedemann** [comment] 2023-01-13 07:48
There are four .spec files in openSUSE, that use `%{_smp_build_ncpus}` directly, e.g.
https://code.opensuse.org/package/python3-pyside6/blob/ad8e8792e6ed522cb99332637de53ce6ff5b93f1/f/python3-pyside6.spec#_226

Maybe instead of 0576d24756fe975d890f5535a21cfdfd35fc2ca4, we could redefine `%_smp_build_ncpus` to `$RPM_BUILD_NCPUS` ?

**Comment by pmatilai** [comment] 2023-01-13 08:26
That would break the macro for anybody using it outside the build scriptlets, which is an entirely legit thing to do. You'll need to fix those specs instead.

**Comment by bmwiedemann** [comment] 2023-01-20 08:19
It seems, `$RPM_BUILD_NCPUS` is not set in our older distributions that have rpm-4.14.3. What would be the best way to have https://github.com/mesonbuild/meson/blob/c754f9076/data/macros.meson#L43 be reproducible on both 4.14 and 4.18 ?

**Comment by pmatilai** [comment] 2023-01-20 13:37
Yep, it's not exactly a big change: d97d7b71de158660eb96b4f11d40b6626b85521a

**Comment by bmwiedemann** [comment] 2023-01-29 08:32
Found another problematic case:
https://code.opensuse.org/package/ocaml-rpm-macros/blob/819e56/f/ocaml-rpm-macros.spec#_464

`'%%{?_smp_mflags}'` 
becomes
`'-j${RPM_BUILD_NCPUS}'` and the variable does not get expanded now, causing a compilation failure. I guess, using double-quotes should fix it.

**Comment by bmwiedemann** [comment] 2023-02-07 09:22
And more trouble from
https://codeberg.org/cunix/vendored_licenses_packager/src/branch/main/macros.vendored_licenses_packager#L18
that injects a random tmp path into the .src.rpm of [dnscrypt-proxy](https://code.opensuse.org/package/dnscrypt-proxy/tree/master)

**Comment by pmatilai** [comment] 2023-03-30 11:17
The reported and most glaring issue with %{_smp_mflags} was addressed in 4.18.x, closing but acknowledging that we may need something further around this.

**Closed by pmatilai** 2023-03-30 11:17 UTC
Labels: REGRESSION

**Comment by bmwiedemann** [comment] 2023-08-15 12:00
Found another reproducibility problem with expanded .spec in
https://code.opensuse.org/package/texlive/blob/d820a867c61524278af352b4febbb115e9dad08f/f/texlive.spec#_287
```spec
%{expand: %%global options %(mktemp /tmp/texlive-opts.XXXXXXXX)}
```

**Comment by bmwiedemann** [comment] 2023-08-23 03:56
found another breakage:
`sed -i -e 's/-j2/%{?_smp_mflags}/' setup.py`
in https://github.com/bmwiedemann/openSUSE/blob/master/packages/p/python-python-poppler/python-python-poppler.spec#L61

**Comment by pmatilai** [comment] 2023-08-23 06:50
Yes, there will be any number of ways the parsed spec inclusion can trip up bit-for-bit differences. "Breakage" is a strange and strong word for it, another angle to look at it is to use it as a tool to help reproducability: if the parsed spec (which is what the build will actually use, after all) differs it's acts as a warning that requires investigation. Some of which will be false positives, like mktemp.
