### ISSUE TITLE
[regression?] rpm 4.17 can't find group declared inside sceleton package

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1789] opened 2021-10-01 06:46 UTC
There is a package "setup" which contains sceleton files /etc/shadow, /etc/shadow, /etc/passwd, /etc/group etc.
Files /etc/shadow and /etc/gshadow are owned by root:shadow:
%attr(0440,root,shadow) %config(noreplace,missingok) %{_sysconfdir}/shadow
%attr(0440,root,shadow) %config(noreplace,missingok) %{_sysconfdir}/gshadow

Group shadow is defined inside those sceleton files.

rpm 4.16 worked ok, but rpm 4.17 cannot find group shadow and uses root.

nscd is not running.

**Comment by ffesti** [comment] 2021-10-01 09:18
This is caused by RPM no longer using the user and group information from out side of the change root. Earlier versions were not properly using the inside files in all cases.

The uid and gid of these files are set before they are moved in place. So the shadow group does not exist yet. While this may have worked previously by using the gui from the installing system this is only working "by accident" as the system likely used the same gid. But if the installation was being run from a system with a different gui for `shadow` the file would end up with the wrong group - which is may be a security concern.

I did not find more information on this change but f9c7b53f50adc129baee809692d4c80b3bd15432 looks like it would have that effect. May be @pmatilai has some pointers.

`chgrp` in the `%post` scriptlet should do the trick - although I admit it is not a great solution


So I'd say this is an intentional behaviour change.

**Comment by pmatilai** [comment] 2021-10-01 09:50
Commit f9c7b53 is supposed to be a no-op, so if that is the thing changing behavior then we need to look at it, I don't remember any intentional change to this effect anyway. That doesn't change the fact that rpm cannot bootstrap user/group info, never could.

**Comment by ffesti** [comment] 2021-10-01 13:19
Oh, right. The patch does only move the `rpmugInit` call to later. I first thought it now does that whenever entering the chroot and was wondering why the commit message is more vocal about that.

I still have this vivid memory of rpm no longer using the the files from outside the chroot. But I can't find anything to support that... 

Stiil the change may lead to the information about the `shadow` group being flushed out of memory without it being read in from the outside system. Flushing it at the very beginning it may allow the group to be read in again. This may explain the difference in behaviour - if there really is any. It could also be that the group was created by another package in previous releases - or order of installation with such a package has changed.

**Comment by DemiMarie** [comment] 2021-10-01 13:42
> Commit [f9c7b53](https://github.com/rpm-software-management/rpm/commit/f9c7b53f50adc129baee809692d4c80b3bd15432) is supposed to be a no-op, so if that is the thing changing behavior then we need to look at it, I don't remember any intentional change to this effect anyway. That doesn't change the fact that rpm cannot bootstrap user/group info, never could.

What is the “correct” way to do this?  Explicit chown in a postinst script?

**Comment by mikhailnov** [comment] 2021-10-02 05:02
> `chgrp` in the `%post` scriptlet should do the trick - although I admit it is not a great solution

Yeah, it is what I did, but in %posttrans, to lighten dependency graph. But the warning from rpm is still present.

> I still have this vivid memory of rpm no longer using the the files from outside the chroot. But I can't find anything to support that...

+1, I have the same thoughts

**Comment by mikhailnov** [comment] 2021-10-02 05:09
> > Commit [f9c7b53](https://github.com/rpm-software-management/rpm/commit/f9c7b53f50adc129baee809692d4c80b3bd15432) is supposed to be a no-op, so if that is the thing changing behavior then we need to look at it, I don't remember any intentional change to this effect anyway. That doesn't change the fact that rpm cannot bootstrap user/group info, never could.
> 
> What is the “correct” way to do this? Explicit chown in a postinst script? Write the files using Lua in a pretrans script?

Is lua in rpm able to call chown() without the chown usitility from coreutils being present in the new chroot?

**Comment by mikhailnov** [comment] 2021-10-02 05:10
by the way, I am not sure that root:shadow owner of /etc/shadow makes sense, Fedora uses just root:root

**Comment by pmatilai** [comment] 2021-10-04 06:35
> Is lua in rpm able to call chown() without the chown utility from coreutils being present in the new chroot?

Ability to do stuff without external tools is the raison d'être for Lua in rpm. Yes, there's posix.chown() in our Lua environment.

**Comment by ffesti** [comment] 2021-10-04 07:11
It won't solve the issue though, as the group still doesn't exist when the files are created. Guess something like `echo "shadow:x:404:" >> /etc/group` in %pre might do the trick.

**Comment by mikhailnov** [comment] 2021-10-04 11:54
> It won't solve the issue though, as the group still doesn't exist when the files are created

But it is possible to chown by a numeric UID/GID, isn't it?

**Comment by pmatilai** [comment] 2021-10-05 06:46
It is, but it wont suppress the warning.

**Comment by pmatilai** [comment] 2023-07-04 09:55
Fixed by f3eaeeb7341085e1850e914350cf1f33d538320d

**Closed by pmatilai** 2023-07-04 09:55 UTC
