### ISSUE TITLE
The SCC breaking code in the ordering algorithm should break weak dependencies first

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm#2111] opened 2022-06-28 12:44 UTC
The code should break weak dependencies before breaking normal dependencies. It currently seems to just handle prereqs in a special way.

See https://github.com/openSUSE/libsolv/issues/501 for a real life example where this popped up.

**Comment by sshedi** [comment] 2022-06-28 12:46
Thanks @mlschroe for creating the issue.

**Comment by pmatilai** [comment] 2022-06-28 13:12
Yup. This is actually a duplicate of #1346 so I'll close this one.

**Closed by pmatilai** 2022-06-28 13:12 UTC
