### ISSUE TITLE
No build-in processing for multiple occurrences of an option with the same name

### ISSUE THREAD

**Issue by rhabacker** [rpm-software-management/rpm#2448] opened 2023-03-23 08:51 UTC
Attempting to process multiple occurrences of an option with the same name with the available rpm macros always returns the last occurrence of the specified option, as the following example shows:

```sh
$ rpm --version
RPM version 4.14.3

$ rpm --define='%_macro(D:) %(echo " option -D: %{-D:%{-D*}}")'  --eval "%_macro -Dxxx=aaa -Dyyy sdsdsd"
 option -D: -Dyyy
```
An evaluation of the [available](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/macros.md) rpm macros for accessing macro parameters with: 
```sh
$ rpm --define='%_macro(D:) %(echo -e " name: %0 \\n non-option-count: %# \\n non-option-params: %* \\n all-params: %** \\n option -D: %{-D:%{-D*}}")'  --eval "%_macro -Dxxx=aaa -Dyy sdsdsd"
 name: _macro 
 non-option-count: 1 
 non-option-parameter: sdsdsd 
 all parameters: -Dxxx=aaa -Dyyy -- sdsdsd 
 Option -D: -Dyyy
```
shows that the requested option is basically available only through `%**` but requires additional processing to extract the multiple occurrences of the relevant option. It would therefore be helpful if rpm had support for this case.

This case has come up when revising an rpm macro for cmake support at the mingw project on build.opensuse.org, where single options would have to be processed in the macro in question but other options that may occur multiple times would have to be passed to cmake.

**Comment by pmatilai** [comment] 2023-03-23 10:30
Yes, a known limitation, this is duplicate of #546 but before just now it had a strange summary which made it hard to discover (I only found it myself because I knew it was there)

**Closed by pmatilai** 2023-03-23 10:30 UTC
