### ISSUE TITLE
[RFE] Implement something like config(neverreplace) that won't replace config file ever

### ISSUE THREAD

**Issue by kkaarreell** [rpm-software-management/rpm#2135] opened 2022-07-29 10:42 UTC
`config(noreplace)` won't prevent config file update if it hasn't been customized by the user.
However, sometimes it would be good to always preserve former config file, e.g. in a situation when new version is introducing new application data format. For example as opencryptoki did, see https://bugzilla.redhat.com/show_bug.cgi?id=2044179#c15 for details.

The requested functionality would preserve the original config file and install the new one as .rpmnew.

**Comment by dmnks** [comment] 2022-08-01 12:21
This seems like a no-brainer, to have an option like this, yet it seems there's no facility in place right now... Needs a closer look, assigning to myself.

**Comment by dmnks** [comment] 2022-08-01 12:29
Basic workaround right now is along the lines of:
1) Back up the existing file in `%pre` (on upgrade)
2) Restore the backed up file in `%post`, optionally saving the newly installed one as `.rpmnew`, emulating RPM's own backup logic

**Comment by pmatilai** [comment] 2022-08-09 07:10
Yup, but this is a dupe of #152, this goes beyond %config files.

**Closed by pmatilai** 2022-08-09 07:10 UTC
