### ISSUE TITLE
4.18.99: `rpmbuild -bp` no longer allows unpack source tree by %prep execution without checking dependencies

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/rpm#2652] opened 2023-09-08 14:59 UTC
I don;t see anything about that on https://rpm.org/wiki/Releases/4.19.0 so it must be some side effects recent changes.
````console
[tkloczko@pers-jacek SPECS]$ rpmbuild -bp python-fastavro.spec
error: Failed build dependencies:
        python3dist(cython) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(installer) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(lz4) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(pandas) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(python-snappy) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(sphinx-rtd-theme) is needed by python-fastavro-1.8.3-2.fc35.x86_64
        python3dist(zstandard) is needed by python-fastavro-1.8.3-2.fc35.x86_64
````

**Comment by dmnks** [comment] 2023-09-08 15:16
This is intended behavior. The fact that it used to work was *a bug* which was fixed in RPM 4.18.1 through #2271, also mentioned in https://rpm.org/wiki/Releases/4.18.1.

**Closed by dmnks** 2023-09-08 15:16 UTC

**Comment by dmnks** [comment] 2023-09-08 15:27
FTR, if you wish to avoid the check, you can use `--nodeps`. It's also what e.g. `fedpkg prep` does behind the scenes.

**Comment by kloczek** [comment] 2023-09-08 16:29
As long as %build was not executed and there is no such things lik `PrepRequires:` IMO it was not the bug .
`BuildRequires:` literally says that it  defines **build** dependencies
Good that `--nodeps` still is working 😋

**Comment by kloczek** [comment] 2023-09-08 16:29
IMO it would be good to add line about that on https://rpm.org/wiki/Releases/4.19.0
