### ISSUE TITLE
RFE Please add a verb to inhibit macro expansion

### ISSUE THREAD

**Issue by nim-nim** [rpm-software-management/rpm#569] opened 2018-10-07 16:57 UTC
So I have a versy large shell macro, inside an `%{expand}` because it’s full of rpm variables that need interpetation, and I’m sick of the `\` game.

Among lots of other things, this macro needs to generale a `%license <somefile>` in file lists.

And of course that won't work because rpm will try to replace the `%license` tag with the content of the package `%{license}` variable.

My current hack is to do
```sh
while read -r -d $'\\n' f ; do
 (echo -n "%" ; echo "license '${f}'")             >> "%{currenfilelist}"
done <<< ${licensefiles}
```

But it is quite hackish and ugly. An unexpand verb would be much cleaner, and useful elsewhere besides.

**Comment by ignatenkobrain** [comment] 2018-10-07 16:58
doesn't it work if you add more percent signs?

**Comment by nim-nim** [comment] 2018-10-07 17:08
Unfortunately, no, '`%%license` gives the same result as `%license` and `%%%license` just prepends a `%` to the licensing tag value

**Comment by nim-nim** [comment] 2018-10-07 17:10
(I should say that by the time rpm reaches this part in the code flow it has probably several levels of imbricated expands to deal with)

**Comment by pmatilai** [comment] 2018-10-15 09:30
A reproducer please.

**Comment by jasontibbitts** [comment] 2018-10-17 14:49
I though this might show it, but to me it looks like it works as expected; using either three or four percent signs seems correct.  (That's kind of a fun result on its own, though.)  Maybe your situation is more complicated or more nesting is required or something.  That's why it's really important to include some instructions for showing the issue.

```
ἐπιθυμία:~❯ cat *spec
%global try1 echo "%license try1"
%global try2 echo "%%license try2"
%global try3 echo "%%%license try3"
%global try4 echo "%%%%license try4"
%global try5 echo "%%%%%license try5"

Name: pkgname
Version: pkgversion
Release: pkgrelease
Summary: pkgsummary

License: pkglicense

%description
pkgdescription

%prep
%try1
%try2
%try3
%try4
%try5

ἐπιθυμία:~❯ rpmspec -P foo.spec
Name: pkgname
Version: pkgversion
Release: pkgrelease
Summary: pkgsummary

License: pkglicense

%description
pkgdescription

%prep
echo "pkglicense try1"
echo "pkglicense try2"
echo "%license try3"
echo "%license try4"
echo "%pkglicense try5"
```

**Comment by nim-nim** [comment] 2019-02-11 18:39
@jasontibbitts you're missing the expand part in your test

One example of real-world code are
https://pagure.io/go-rpm-macros/blob/master/f/rpm/macros.d/macros.go-rpm.internal#_96

(I really should push it so work can focus on improving the code and making workarounds unnecessary, at least for the fonts sister macro project which is a lot less scary than the golang one, but it's stuck on the remaining small bits of https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/51)

**Comment by pmatilai** [comment] 2019-03-04 13:26
> @jasontibbitts you're missing the expand part in your test

@nim-nim and this is exactly why *you* need to provide an *actual reproducer*. Pointers to macros someplace on the net with random mumblings attached is not a reproducer.

**Comment by ignatenkobrain** [comment] 2019-04-17 07:21
I think this has been long enough in waiting-for-info state. Closing.

**Closed by ignatenkobrain** 2019-04-17 07:21 UTC
Labels: needs reproducer
