### ISSUE TITLE
Queried tag fields not exhibited. Specified package name reported in output

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm#2411] opened 2023-03-05 15:56 UTC
Package specified reported in output

Hello. Noticeable issues:
- Queried **tag fields are not exhibited** along with each reported package name.
- The **specified package name is reported**. Nonetheless in that context, queried tag fields are exhibited. 
```
$ rpm -q --qf %{version} libxcrypt-compat
4.4.33
$ rpm -q --conflicts --obsoletes --requires --recommends --suggests --supplements --qf '%{name} %{version} %{conflicts} %{obsoletes} %{requires} %{recommends} %{suggests} %{supplements} %{enhances}' libxcrypt-compat
libc.so.6()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.25)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.36)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libxcrypt(x86-64) = 4.4.33-4.fc37
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rtld(GNU_HASH)
libxcrypt-compat 4.4.33 (none) (none) libc.so.6()(64bit) (none) (none) (none) (none)
```

**Comment by Ricky-Tigg** [comment] 2023-03-15 15:11
correction | additions of headers representing tags are possible.

**Comment by ffesti** [comment] 2023-10-16 08:07
The issue here is that these tags are arrays and need to be surrounded by square brackets. The CLI params already do that for you. They also include the flags and version while the using the tags directly only gives you the name part of the tripplets. You can just use `%{conflictnevrs}` and friends to get the same thing. See  https://rpm-software-management.github.io/rpm/manual/queryformat.html and `rpm --querytags`.

Closing as not a bug.

**Closed by ffesti** 2023-10-16 08:07 UTC
