### ISSUE TITLE
Parametric macro arguments are not expanded

### ISSUE THREAD

**Issue by ascherer** [rpm-software-management/rpm#127] opened 2017-01-14 05:23 UTC
There seems to be a timing problem when expanding
```
%bcond_without patches
...
%prep
%autosetup -c %{?with_patches:-p1}%{!?with_patches:-N}
```
This was my original version in [sgb.spec](https://github.com/ascherer/sgb/blob/local/sgb.spec) (developed with `debbuild`) where the conditional macro `%{?with_patches:-p1}` does _not_ produce the expected `-p1` option for `%autosetup`, independent of the use of `--without patches` on the CLI.

Using classic `%if..%else..%endif` logic works, but this takes five LOC and I'd rather like the single-line solution.

This occurs with **rpmbuild 4.12.0.1** on **Kubuntu 16.04**.

As an aside I report that adding `BuildArch: x86_64` to `sgb.spec` makes `rpmbuild` ignore the patches completely.

**Comment by pmatilai** [comment] 2017-01-16 06:53
Yup, see also https://bugzilla.redhat.com/show_bug.cgi?id=1397209. Whether it's truly *intentional* I don't know but AFAIK it's always been that way.

Fixing it is a simple matter of:
```
--- a/rpmio/macro.c
+++ b/rpmio/macro.c
@@ -687,8 +687,10 @@ grabArgs(MacroBuf mb, const rpmMacroEntry me, const char * se,
      * Append the results to main argv. 
      */
     {  ARGV_t av = NULL;
-       char *s = xcalloc((lastc-se)+1, sizeof(*s));
-       memcpy(s, se, (lastc-se));
+       char *s = NULL;
+
+       /* Expand possible macros in the arguments */
+       expandThis(mb, se, lastc-se, &s);
 
        argvSplit(&av, s, " \t");
        argvAppend(&argv, av);
```

...but it'd be changing a longstanding behavior and there's no telling what might break if we did that.

**Comment by pmatilai** [comment] 2017-01-16 08:08
Looking at Fedora rawhide specs, at least font packages break with the above change. Pretty much as expected, actually.

**Comment by ascherer** [comment] 2017-01-16 09:05
So it seems I went a bit overboard with [my implementation of `%autosetup` in `debbuild`](https://github.com/ascherer/debbuild/blob/master/debbuild#L810). Interesting though, that the same issue occurred on RH. :wink:

**Comment by pmatilai** [comment] 2017-01-16 10:48
I didn't really mean to, but ended up looking at this a bit more.

It's by no means just the font-packages that break, there are all sorts of other cases too, at least:
- passing arguments starting with "-" by passing them in as macros (%py2_build etc macros, some java packages) which now fail as invalid options. This is basically abuse, using "--" to separate arguments from options actually works but isn't widely known or documented.
- %systemd_user_post macro fails with recursion loop on %{?*}

Breakage on automatic macros is not a big surprise considering this changes scoping rules in some ways.

**Comment by ascherer** [comment] 2017-01-16 12:35
In the particular case of [`%autosetup` in `sgb.spec`](https://github.com/ascherer/sgb/blob/local/sgb.spec#L52), using `-N` or `-p1` depending on the CLI option `--without patches` is utterly redundant, because [the set of patches is commented-out](https://github.com/ascherer/sgb/blob/local/sgb.spec#L31) in the first place.

**Comment by ignatenkobrain** [comment] 2017-01-16 14:01
workaround which I use in `%py3_build` is `%py3_build "--use-cython"` which works....

I would reopen this bug.

**Comment by pmatilai** [comment] 2017-01-16 14:06
Yes the issue is valid regardless of the particular sgb.spec case, reopening.

**Comment by pmatilai** [comment] 2017-01-16 14:12
The case in RH bugzilla kind of highlights the insanity nicely:

`%setup -q %{?rev:-c}`
`%autosetup %{?rev:-c}`

Yes, one is a builtin and the other one is a macro. But I'd be hard-pressed to come up with a *sensible* explanation why those should behave differently.

**Comment by pmatilai** [comment] 2017-03-07 12:33
Fixed in commit 5adc56897b9da5dac49701f704ef54390db57c59 but that actually depends on the three preceding macro changes, there are all sorts of funnies involved.

**Closed by pmatilai** 2017-03-07 12:33 UTC

**Comment by judovana** [comment] 2017-08-16 15:02
Hello!  I have suspicion, that this could raise an regression.
If i  had parametrised macro , which wasusin %1 or so, and I sent %{nil} to that macro, then %1 evaluated as nothing.  Now, %{nil} is evaluated  first, and so nothing goes ot my macro, and so %1 habve nothing to evaluate in. So it stays as %1. Thhoughs?

**Comment by pmatilai** [comment] 2017-08-17 11:49
Yes this will force changes to some existing macros, that is unavoidable.

There are basically two ways to deal with it, which:
a) escape macros in the arguments to prevent expansion, eg %%{nil}
b) adjust the parametrized macro itself, eg in some situations it would be more natural to test for the argument existence instead (eg %{?1} instead of assuming it always exists)

b) is actually the one that allows some level of compatibility between former and new behavior, as %{?1} will do the right thing in both cases if you just drop the "placeholder" %{nil} argument from the caller.

**Comment by judovana** [comment] 2017-08-17 14:09
Ok will try. I'm wonderng how my hackich  sending of parameter's parameter (%%1) will work....  Running test build with https://src.fedoraproject.org/rpms/java-9-openjdk/c/6dd07923a5203651059e28f4c1422a2d862e2d84?branch=f27 now. TY!

**Comment by judovana** [comment] 2017-08-18 10:09
hmm %{?1} did not work. It did not never expanded. is still valid that simple %{?1} is same as %{?1:%1} ?

**Comment by pmatilai** [comment] 2017-08-18 10:25
%{?1} is the same as %{?1:%1}, yes. And sure it works, eg:
```
[pmatilai@sopuli ~]$ rpm --define "foo() %{?1}" --eval "%foo %{nil}"

[pmatilai@sopuli ~]$ rpm --define "foo() %{?1}" --eval "%foo %{_lib}"
lib64
```

However looking at https://src.fedoraproject.org/rpms/java-9-openjdk/blob/6dd07923a5203651059e28f4c1422a2d862e2d84/f/java-9-openjdk.spec...

```
%global post_headless() %{expand:
```

%global does not work correctly with parametric macros in any version of rpm, since the body is expanded at the time of definition instead of time of use as is the case with %defines. And the spec is full of those, combined with some strange %{expand}s and whatnot. This is a sad example of what the misguided "%define is evil and must be replaced by %global" campaign in Fedora has done :(

**Comment by pmatilai** [comment] 2017-08-18 10:27
So... start by changing the %global's of parametric macros to %define(). Many/most of the accompanying %{expand:}s are likely unnecessary and unwanted too.

**Comment by judovana** [comment] 2017-08-18 10:34
Thats baadddd... Very bad.You killed dinamic specfiles.


What I have is:
for suffix in %{build_loop} ; do
mkdir -p %{buildoutputdir $suffix}
pushd %{buildoutputdir $suffix}
....
done

You see that expansion  as is odnenow killed it.

**Comment by judovana** [comment] 2017-08-18 10:40
"%global does not work correctly with parametric macros in any version of rpm, since the body is expanded at the time of definition instead of time of use as is the case with %defines. And the spec is full of those, combined with some strange %{expand}s and whatnot. This is a sad example of what the misguided "%define is evil and must be replaced by %global" campaign in Fedora has done :("

I see. Originally there was deffined, and yes, based on that campaign I put global everywhere. What are the crucial differences then?  

What change will be achived when simply replacing or expandable %global var()   by %deffine() var?

**Comment by judovana** [comment] 2017-08-18 10:41
O, and thank you very much for helping me out!

**Comment by pmatilai** [comment] 2017-08-18 10:54
The crucial difference is right there in the part you quoted:
```
%global does not work correctly with parametric macros in any version of rpm, since the body is expanded at the time of definition instead of time of use as is the case with %defines.
```

So basically you *can* use %global instead of %define, but doing that requires an extra escaping all the macros that are used. And then you need the %expand{} around them because it was already expanded. So lots of unnecessary work and complexity in the spec because of that wholly unnecessary switch to %global.

AFAICS the general pattern is:
```
%global sdkbindir()     %{expand:%{_jvmdir}/%{sdkdir %%1}/bin}
```

...which is the rather hard way to say:
```
%define sdkbindir()     %{_jvmdir}/%{sdkdir %1}/bin
```

For most cases both will work fine with the new rpm too. The biggest difference is the case where %1 might expand to nothing, in which case you need to either escape it with an extra % (so in %global case, there would now be three %-characters!) or have the relevant macro(s) handle the case where %1 is effectively not passed, ie %{?1}.

**Comment by judovana** [comment] 2017-08-18 11:06
I see. I guess when macro is multiline, I still need to use %{expand
....
}


oook?

**Comment by pmatilai** [comment] 2017-08-18 11:16
No, you just need to use trailing ```\``` to indicate line-continuation which is not necessary inside %{...} "block scope".

**Comment by judovana** [comment] 2017-08-18 11:30
Sorry, to clarify again:

%global sdkbindir()     %{expand:
%{_jvmdir}/%{sdkdir %%1}/bin
%{_jvmdir}/%{sdkdir %%1}/bin
}
==
%define sdkbindir()     %{expand:
%{_jvmdir}/%{sdkdir %%1}/bin
%{_jvmdir}/%{sdkdir %%1}/bin
}
==
%define sdkbindir()    \
 %{_jvmdir}/%{sdkdir %1}/bin \
 %{_jvmdir}/%{sdkdir %1}/bin 

==
%define sdkbindir()     %{
%{_jvmdir}/%{sdkdir %1}/bin
 %{_jvmdir}/%{sdkdir %1}/bin
}

where the initial global is missused
right?

**Comment by pmatilai** [comment] 2017-08-18 11:51
```
%define mymacro() \
echo foo\
echo bar
```
...is the line-continuation syntax.

As for the rest, it depends on what you need to do with it. If the arguments are always non-%{nil} then there's nothing you need to do. If arguments can be %{nil} (or otherwise empty), then you have two choices:

1) escape the argument in the *caller*, eg "%sdkbindir %%{nil}". If you need to pass unexpanded macros through several layers of macros as seems to be the case, then you need to escape them at each caller. So in the sdkbindir() case, you'd use %%{1} in the calls to %sdkdir.
2) handle the "missing" argument in the parametric macro (ie callee, instead of caller, basically), by using ?-conditionals.

**Comment by judovana** [comment] 2017-08-18 11:58
Thank you. They can be nil, so  ? approach is clear way.
Now building withmost direct: https://src.fedoraproject.org/rpms/java-9-openjdk/c/abdb6134df8fd6e458e41d9a020274dd441ed2e7?branch=f27  lets see again. 

The approach, once tuned here, will need to be backport to jdk8

**Comment by pmatilai** [comment] 2017-08-18 12:09
Yes, things actually become more natural when empty arguments are handled as such. But even positive change can be a major PITA if it comes at the wrong time, know the feeling... 

I'd recommend trying to eliminate those leftover %expand's and double %%-s necessiated by %global use, those only make reading and understanding the whole thing more difficult.

**Comment by judovana** [comment] 2017-08-18 12:25
> I'd recommend trying to eliminate those leftover %expand's and double %%-s necessiated by %global use, those only make reading

Thats plan to do. But in small steps.  It may be easy to cause some really hard to find issues.

>  and understanding the whole thing more difficult.


Thats long term goal!  With rpm development in progress and some hidden stuff documentation not exactly easy t find... neverending goal:)

**Comment by judovana** [comment] 2017-08-18 12:27
The:

%define sdkbindir() %{
%{_jvmdir}/%{sdkdir %1}/bin
%{_jvmdir}/%{sdkdir %1}/bin
}

Is correct right?

**Comment by pmatilai** [comment] 2017-08-18 12:50
Not really, the surrounding %{ ... } will end up in the macro body literally which is unlikely to be what you want. It's not a general block construct in the sense you'd find in eg C. Use the line-continuations instead, eg

```
%define sdkbindir()\
%{_jvmdir}/%{sdkdir %1}/bin\
%{_jvmdir}/%{sdkdir %1}/bin
```

**Comment by judovana** [comment] 2017-08-18 12:56
I consider the \\ syntax as easy to make an error and easy to oferlook when readed. So i would prefer matching bracket rather. Thanx.

hmm, the build failed. %1 leaked in again. Looks my small steps do not work as I hoped...

**Comment by judovana** [comment] 2017-08-18 13:16
hmmm. Moving in that, and started to slowly get in same maze where I was when deffine was  used instead of  global - error: Too many levels of recursion in macro expansion. It is likely caused by recursive macro declaration.

**Comment by pmatilai** [comment] 2017-08-18 14:00
It's easy to cause a recursive definition by mistake, but after seeing the jdk spec... the macros nest deeper than anything else I've seen in rpm macro usage. It's quite possible that you're running into the artificial limit of 16 nesting levels.

I initiated a scratch-build where the limit is raised to 64 if you want to try it out:
https://koji.fedoraproject.org/koji/taskinfo?taskID=21305568

**Comment by judovana** [comment] 2017-08-18 15:12
Yup, that version did not complained about recursive macros. The increased limit would be nice.

**Comment by judovana** [comment] 2017-08-24 18:02
Hi again. I enhanced the f27+f28 as we agreed here, and they works fine.

However, when I  backported the changes to f25+f26, the construct which was sending in the $variable in build and install  is not expanded at all. Do you have some hint how to backport the changes to older rpmbuild?

**Comment by pmatilai** [comment] 2017-08-28 09:12
Impossible to say without specific information. While most things can be written in a backwards compatible way, it's entirely possible some things cannot. I'd leave the older versions alone...

**Comment by PaulSD** [comment] 2022-10-14 17:08
For reference, I've found an ugly hack to work around some of these issues on RPM 4.11.3 (RHEL7).

Example macros that work in current RPM but break in RPM 4.11.3:
```
%define nested() %{echo:%{?1}}
%define outer() %{nested -- %{?1}}
%{outer -- test}
```
(In 4.11.3, `%{?1}` in the `nested` macro expands to `%{?1}` which leads to an infinite loop of expansion)

Hack to make it work in RPM 4.11.3:
```
%define preExpand(-) %{expand:%%{%**}}
%define nested() %{echo:%{?1}}
%define outer() %{preExpand nested -- %{?1}}
%{outer -- test}
```
(The `preExpand` macro in `outer` expands `%(?1}` before expanding `%{nested -- ...}`, which avoids the infinite loop.)

The `(-)` in the `preExpand` macro definition is a hack to get it to read the options into `%**` (which is an undocumented macro containing the unparsed options list) without parsing the options and overwriting %1, %2, etc.  This causes `rpmbuild` in 4.11.3 to print "error: Unknown option" every time it expands the "preExpand" macro, although that error message is harmless.

If "--" is always used when passing arguments to parameterized macros then this `sed` regex can be used to inject `preExpand` into all of the outer macros in the spec file: `s/{\([^ {]\+\) -- /{preExpand \1 -- /g`

**Comment by judovana** [comment] 2022-10-17 11:29
thank you for heads up/
