### ISSUE TITLE
Test [Dependency generation] fails on Fedora Rawhide due to fakechroot problem

### ISSUE THREAD

**Issue by filbranden** [rpm-software-management/rpm#511] opened 2018-08-14 05:02 UTC
The problem is due to `/usr/bin/install` crashing with a segmentation fault, called from inside `data/SPECS/filedep.spec`.

The problem has to do with:
* libattr 2.4.48 (some change from 2.4.47)
* SELinux enabled (which means files have extended attributes and `/usr/bin/install` will try to copy them)
* fakechroot is in use, and attribute operations (such as `lsetxattr` used by `/usr/bin/install`) will break when libattr 2.4.48 is in use.

See dex4er/fakechroot#57 for the issue I filed in fakechroot.

I wanted to file this here as well, in case others find this same failure I did. Not sure if we would want to work around it here somehow... Would be better if this got fixed upstream.

**Comment by pmatilai** [comment] 2018-08-15 10:54
Yup, been there, hit that so known issue for me at least, but certainly better visibility here than in my head :) Thanks for filing the upstream bug too.

**Comment by filbranden** [comment] 2018-09-04 19:34
Fixed in libattr:
http://git.savannah.nongnu.org/cgit/attr.git/commit/?id=14adc898a36948267bfe5c63b399996879e94c98

I proposed a backport for the Fedora libattr RPM:
https://src.fedoraproject.org/rpms/attr/pull-request/2

**Comment by n3npq** [comment] 2018-09-05 01:32
Have another flaw reproducer using fakechroot with rpm4 "make check"

0) Create (and use) a symlink to the directory where rpm just built is under test.
1) Run "make check" in rpm4.

Hint: pseudo from the Yocto Project (written and maintained by Peter Seebach) is a mature and reliable replacement for fakechroot.

**Comment by pmatilai** [comment] 2018-09-05 08:56
Nice, big thanks @filbranden for your efforts to get it addressed!

**Comment by pmatilai** [comment] 2018-10-03 11:28
FWIW, this has been since fixed in Fedora rawhide and 29, but 28 still suffers from it. Not that it's a bug that many people will see...

**Comment by pmatilai** [comment] 2019-10-15 12:56
Okay I think this one has outlived its usefulness, Fedora 28 being EOL and all.
Thanks again for helping get this addressed.

**Closed by pmatilai** 2019-10-15 12:56 UTC
Labels: INFO
