### ISSUE TITLE
failures in buildah(chroot) environment - is it ok to ignore?

### ISSUE THREAD

**Issue by shivakumargn** [rpm-software-management/rpm#1456] opened 2020-12-06 13:23 UTC
I am using RPM version 4.15.1 on fedora 31.
Attempting to build CentOS 7 based image using buildah from scratch.

Installing below packages
`glibc-2.17-317.el7.x86_64.rpm bash-4.2.46-34.el7.x86_64.rpm ncurses-libs-5.9-14.20130511.el7_4.x86_64.rpm`

Leads to errors as mentioned in https://github.com/rpm-software-management/rpm/issues/1077

`error: setexecfilecon: (/usr/sbin/glibc_post_upgrade.x86_64) No such file or directory`

Is it ok to ignore the error while creating the image?

**Comment by pmatilai** [comment] 2020-12-10 12:24
How could we possibly know?

It does *look* like a duplicate of #1077, and with no evidence to contrary that's what I'll assume it is.

**Closed by pmatilai** 2020-12-10 12:24 UTC
