### ISSUE TITLE
out-ot-tree build

### ISSUE THREAD

**Issue by masahir0y** [rpm-software-management/rpm#1851] opened 2021-11-30 13:40 UTC
I am not sure if this is supported in the first place,
but building in a seprate directory fails.

Let's say the source directory is located in ~/ref/rpm,
and I want to put build artifacts in /tmp/build-rpm/.

I did:

 $ cd ~/ref/rpm
 $ git clean -d -f -x
 $ ./autogen.sh --noconfigure
 $ mkdir /tmp/build-rpm
 $ cd /tmp/build-rpm
 $ ~/ref/rpm/configure
 $ make

Then, I got:
 
 
make[2]: Leaving directory '/tmp/build-rpm/build'
Making all in scripts
make[2]: Entering directory '/tmp/build-rpm/scripts'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/build-rpm/scripts'
Making all in fileattrs
make[2]: Entering directory '/tmp/build-rpm/fileattrs'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/build-rpm/fileattrs'
Making all in docs
make[2]: Entering directory '/tmp/build-rpm/docs'
Making all in man
make[3]: Entering directory '/tmp/build-rpm/docs/man'
make[3]: *** No rule to make target 'fr/rpm.8', needed by 'all-am'.  Stop.
make[3]: Leaving directory '/tmp/build-rpm/docs/man'
make[2]: *** [Makefile:496: all-recursive] Error 1
make[2]: Leaving directory '/tmp/build-rpm/docs'
make[1]: *** [Makefile:1300: all-recursive] Error 1
make[1]: Leaving directory '/tmp/build-rpm'
make: *** [Makefile:746: all] Error 2

**Comment by pmatilai** [comment] 2021-12-02 08:44
Out-of-tree builds are expected to work, so it'd be a bug someplace, actually a regression. 
Our CI does "make distcheck" which also does an out-of-tree build so this shouldn't be possible, but distcheck may be using some different flags someplace or something. @ffesti this looks like something from the recent docs rework so I'll assign to you.

**Closed** 2021-12-16 11:55 UTC
Labels: REGRESSION
