### ISSUE TITLE
Please support smaller build-ids

### ISSUE THREAD

**Issue by espindola** [rpm-software-management/rpm#950] opened 2019-11-23 01:30 UTC
Currently rpm requires build ids to be between 16 and 64 bytes in size:

https://github.com/rpm-software-management/rpm/blob/b7d427728b8ba8734ba47d51849a5736bdd727cd/build/files.c#L1883

Since the main intention of build-id is to avoid accidentally using the wrong binary, lld defaults to xxhash which is much faster than md5 or sha1 but only 8 bytes long.

**Comment by rpm-maint** [comment] 2019-11-23 14:32
On Fri, 2019-11-22 at 17:30 -0800, Rafael Ávila de Espíndola wrote:
> Currently rpm requires build ids to be between 16 and 64 bytes in size:
> 
> https://github.com/rpm-software-management/rpm/blob/b7d427728b8ba8734ba47d51849a5736bdd727cd/build/files.c#L1883
> 
> Since the main intention of build-id is to avoid accidentally using the wrong binary, lld defaults to xxhash which is much faster than md5 or sha1 but only 8 bytes long.

Although technically build-ids can be shorter than 16 bytes, I am not
sure 8 bytes are enough for a globally unique identifier. That is just
64 bits. The lower bound of 16 bytes is because normally you seem to
need at least 128 bits to be sure you can generate a universally unique
identifier. Are you sure xxhash generates sufficiently unique hashes
using just 8 bytes?

Note that the comment just above that line says:

   We want at least a length of 2 so we have at least a xx/yy (hex)
   dir/file. But reasonable build-ids are between 16 bytes (md5 is 128
   bits) and 64 bytes (largest sha3 is 512 bits), common is 20 bytes
   (sha1 is 160 bits).

I don't think a secure hash is necessary to generate a build-id, so
using a non-cryptographic hash function should be fine. But I am a
little concerned about the low number of bits of the hash function.

Cheers,

Mark

**Comment by espindola** [comment] 2019-11-23 17:53
This is the birthday problem, so a good 64 bit hash needs about 32 bit worth of hashes for a collision. Note that there is precedent for using only 64 bits. The dwarf standard (http://www.dwarfstd.org/doc/DWARF5.pdf section 7.32  "Type Signature Computation") uses the last 8 bytes of md5 for type signatures.

As for the quality, I think xxhash is very good (http://cyan4973.github.io/xxHash/) , but I don't have any detailed knowledge of hashes.

If we really need 128 bits, which hash would you suggest for a fast buildid? Farmhash comes to mind.

**Comment by rpm-maint** [comment] 2019-11-25 11:20
On Sat, 2019-11-23 at 09:53 -0800, Rafael Ávila de Espíndola wrote:
> 
> If we really need 128 bits, which hash would you suggest for a fast
> buildid? Farmhash comes to mind.

128 bits is the minimum that GNU binutils ld and gold support, you can
choose between uuid (128bits), md5 (128bits) and sha1 (160bits). Where
sha1 is the default. If you want maximum compatibility you would use a
hash that is 160bits/20bytes. I have seen code that simply hardcodes
build-ids being 20 bytes (those should be fixed of course, but that
might take time).

But I don't know if 64bits/8bytes is enough, assuming the hash code is
good the the birthday problem probabilty table shows the difference
between using 64bit and 128bit hashes:
https://en.wikipedia.org/wiki/Birthday_problem#Probability_table

I'll ask some people who have tried to index all executables of a
distribution what number of executables they have encountered.

**Comment by fche** [comment] 2019-11-25 17:16
>  Note that there is precedent for using only 64 bits. The dwarf standard (http://www.dwarfstd.org/doc/DWARF5.pdf section 7.32 "Type Signature Computation") uses the last 8 bytes of md5 for type signatures.

I see your point, but it is likely that the number of binaries in an OS distribution is orders of magnitude greater than the number of distinct type declarations / signatures of its source code.  And AIUI, the type signature code is meant for use primarily for indexing within or amongst a small set of related dwarf files already, i.e., another level of buildid type indexing would already have been applied to tell them apart.

This is not to say that rpm per se should be enforcing distro-scale concerns - but if it doesn't, some other piece of distro releng tooling must.  An 8-byte (16-hex-char) code is likely too small within a single distro/arch, never mind globally.  (I'm collecting some buildid population figures for a slice of fedora via debuginfod as we speak.)

**Comment by MaskRay** [comment] 2019-11-26 09:01
@espindola Did you use lld that is newer than 2019-11-11? The LLVM SHA1 was optimized recently https://github.com/llvm/llvm-project/commit/43ff63477256d584cf506dba0c222c28231b0ccc . It is not included in llvm 9.*, though.

**Comment by espindola** [comment] 2019-11-26 17:24
Yes, I used ac37755c60ba19103f08f04d07ca8f1d640153d6.
It is impressive how fast sha1 is now, but it is still much slower than xxhash. Linking a release version of scylla I got

none 2.022252056 seconds
fast 2.061659922 seconds
md5  2.740843349 seconds
sha1 2.318114449 seconds

**Comment by fche** [comment] 2019-11-26 20:00
To complete my partial distro-wide buildid analysis, for fedora30 x86-64
(from its first branch last summer till the present) all built packages add up to apprx. 780 GB of build artifacts.  Based on an extrapolation from a single-day 'compose' set of one version of each package, this maps to *very roughly* 600 million distinct buildids over the course of a distro for that arch, and it still has another eight months of lifespan left.

Looking at the birthday-attack probability table, the probability of collisions at that kind of scale (10**9) with a 64-bit hash is already on the several-percent level.

**Comment by fche** [comment] 2019-11-26 20:01
To complete my partial distro-wide buildid analysis, for fedora30 x86-64
(from its first branch last summer till the present) all built packages add up to apprx. 780 GB of build artifacts.  Based on an extrapolation from a single-day 'compose' set of one version of each package, this maps to *very roughly* 600 million distinct buildids over the course of a distro for that arch, and it still has another eight months of lifespan left.

Looking at the birthday-attack probability table, the probability of collisions at that kind of scale (10**9) with a 64-bit hash is already on the several-percent level.

**Comment by espindola** [comment] 2019-11-26 20:18
Fair enough.  Fell free to close this. I will forward your analysis to the lld developers.

**Comment by espindola** [comment] 2019-11-26 20:23
lld bug: https://bugs.llvm.org/show_bug.cgi?id=44138

**Comment by fche** [comment] 2019-11-26 21:07
Argh, very sorry @espindola but I was 3 orders of magnitude too high with my extrapolated numbers.  I hereby hand back my math card.  The collision probability is more in the 10e-6 range.

**Comment by pmatilai** [comment] 2019-11-27 12:01
Non-unique build-ids become file conflicts in rpm, and end up preventing installations packages when the build-id links are in the main package, ie at least Fedora + RHEL and derivates. That's why strong hashes in build-id calculation are a must.

**Closed by pmatilai** 2019-11-27 12:01 UTC

**Comment by rpm-maint** [comment] 2019-11-27 13:33
Hi Frank,

Thanks so much for trying to come up with actual numbers!

On Tue, 2019-11-26 at 13:07 -0800, Frank Ch. Eigler wrote:
> Argh, very sorry @espindola but I was 3 orders of magnitude too high
> with my extrapolated numbers.  I hereby hand back my math card.  The
> collision probability is more in the 10e-6 range.

This seems mood since the issue is already closed and lld will probably
switch to a 128 or 160 bit build-id anyway. But I am still interested
in the actual numbers and I am now also a little confused.

When you say you were off by 3 orders of magnitude to you mean that for
one architecture (x86_64) and one release (fedora 30) you estimate that
there are ~600.000 build-ids (instead of ~600.000.000) because that is
the number of executable artifacts? Or that you extrapolated it (which
number?) wrongly when looking at the number of arches (i386 and x86_64
can be installed concurrently) and actual distros (3 normally) that
overlap in maintenance?

Or asked differently, which number of build-ids are you expecting to
come to a collision probability of 10e-6 when the build-id is just
64bits?

Thanks,

Mark

**Comment by fche** [comment] 2019-11-27 14:17
I extrapolated incorrectly to 600 million because of an off-by-1024 error in my calculations, not because of other architectures / releases.  Those add a factor of 20ish (for fedora).

**Comment by fche** [comment] 2021-05-31 23:04
By the way, just following up with fresher data by checking out the https://debuginfod.fedoraproject.org/metrics.  We're counting 15.7 million distinct buildids across 3+ fedora (32,33,34,rawhide) complete build histories across all arches, which is about 24 bits = 3 bytes.  The traditional 20-byte buildid hash provides ample uniqueness probability, but so could something considerably shorter.
