### ISSUE TITLE
Python module's name changed unnecessarily, making it impossible to express dependencies on it

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/rpm#373] opened 2017-12-22 02:00 UTC
https://github.com/rpm-software-management/rpm/commit/2797d00ecd224a59a8ca967f40240e827ff31c69 was an awful change. Please revert it.

It doesn't matter that you've never published to pypi; so long as you install an egg-info file people will rely on its contents. I was expressing a dependency on 'rpm-python' for a fedmsg consumer that uses the module:

* https://pagure.io/fedora-qa/relvalconsumer/blob/d3ab5df439c3849558afb7502cae00ae991de4be/f/install.requires
* https://pagure.io/fedora-qa/relvalconsumer/blob/d3ab5df439c3849558afb7502cae00ae991de4be/f/setup.py

Only now that doesn't work, and I can't possibly fix it, because the module's "name" is one thing in F26 but another thing in F27. I need this consumer to work on both F26 and F27, at least temporarily, because the production deployment of openqa is on F26, but the staging one is on F27.

**Comment by n3npq** [comment] 2017-12-22 07:17
There's several ways to solve a renaming: pick you poison wrto your packaging policy.

Add a Provides: for the F26 name to the F27 package (or vide versa).

You can also add a file dependency, or add a Newer! Better! Besetest! name to both packages/modules.

**Comment by AdamWill** [comment] 2017-12-22 17:18
This isn't about package dependencies. It's about Python ecosystem dependencies. These particular dependencies are read by setuptools/distutils, and by tox.

**Comment by n3npq** [comment] 2017-12-22 18:17
So the problem is the name of a directory on some Python loader search path?

Sounds like a symlink would fix the renaming ...

**Comment by AdamWill** [comment] 2017-12-22 18:37
No. No, not that either. The *code* works fine, if it actually gets run, because the name of the module itself (`rpm`) has not changed. This is about bits of Python-ecosystem infrastructure that allow for the expression and checking of dependencies. Specifically, in my case, `setuptools` and `tox`, but there are certainly others.

The way I understand it, these are usually implemented via the egg format. To look at it in Fedora / RH terms, by policy Python library packages for those distros have to include egg files, where the library's build scripts produce them:

https://fedoraproject.org/wiki/Packaging:Python#Files_to_include

"*.egg-info files or directories. If these are generated by the module's build scripts they must be included in the package because they might be needed by other applications and modules at runtime."

The python(2,3)-rpm packages *do* include these egg files:

    [adamw@adam openqa (master %)]$ rpm -ql python2-rpm | grep egg
    /usr/lib64/python2.7/site-packages/rpm-4.14.0-py2.7.egg-info
    [adamw@adam openqa (master %)]$ rpm -ql python3-rpm | grep egg
    /usr/lib64/python3.6/site-packages/rpm-4.14.0-py3.6.egg-info

and the 'name' in question is included in those. On a Fedora Rawhide system (27 is the same):

    [adamw@adam openqa (master %)]$ grep Name /usr/lib64/python2.7/site-packages/rpm-4.14.0-py2.7.egg-info
    Name: rpm

But on a Fedora 26 system:

    [adamwill@openqa01 ~][PROD]$ grep Name /usr/lib64/python2.7/site-packages/rpm_python-4.13.0.2-py2.7.egg-info
    Name: rpm-python

*That* is the problem.

When you're creating a Python module, if you do the normal thing and create a setuptools-style `setup.py` for it, you can express dependencies in this:

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies

When setuptools is resolving these dependencies, it uses the 'name' expressed in the egg file. Which is the name *declared* in the `setup.py` for the library. That is, if I put `install_requires=['rpm']` in a `setup.py` file, when I try to install that Python library, setuptools will be satisfied if there is a library installed whose egg file declares its name to be `rpm`. *Not* if there is a library installed which would be loaded by an `import rpm` statement in Python code. So for older versions of RPM, if you want to declare that your Python project requires the Python RPM library in its `setup.py`, you have to do `install_requires=['rpm-python']`. Doing `install_requires=['rpm']` *does not work*: trying to install the library will fail, claiming no library called `rpm` is available or can be installed.

**Comment by AdamWill** [comment] 2017-12-22 18:41
BTW, I'm around on Freenode and RH internal IRC (adamw on both) for anyone who wants to talk about this in real time. Also tagging @Conan-Kudo and @ffesti as the committers.

**Comment by AdamWill** [comment] 2017-12-22 18:45
Here's a commit that had to write a whole extra function in its `setup.py` to get around this:

https://github.com/rebase-helper/rebase-helper/commit/2f1401c0adfc139aa3ecc12cdc21086d2fe69ac9

which is not an approach I can easily take, because I want to share the same requirements between `setup.py` and tox, so I put them in a plain text file and have both `setup.py` and `tox.ini` read them out of the file - but obviously I can't do both of those things together. The way tox works, I'd have to write a *different* hack for tox.

**Comment by Conan-Kudo** [comment] 2017-12-22 19:00
@AdamWill 

In almost every distribution (excluding Fedora) that was using Python bindings, they were _not_ using the setuptools build. In fact, to date, I have not encountered any significant applications that declared `rpm` or `rpm-python` as a dependency in setuptools because most distributions installed the bindings via the Makefile rather than setuptools, which meant the information wasn't even available.

As we switched to the setuptools build in Mageia and I switched the build in openSUSE for RPM 4.14, I elected to fix the setuptools data because everyone expected the python bindings information to match the module name.

Since we don't publish to PyPI for very obvious reasons, any reliance on setuptools information was always hokey.

I continue to stand by my decision to rename the module because most application developers expected the Python module name to be `rpm`.

**Comment by AdamWill** [comment] 2017-12-22 19:07
"Since we don't publish to PyPI for very obvious reasons, any reliance on setuptools information was always hokey."

The document I linked above *specifically states that it is reasonable to express dependencies on things that aren't in pypi*. In a section titled...[Dependencies that aren't in PyPI](https://setuptools.readthedocs.io/en/latest/setuptools.html#id13).

"Most developers expect the name to be Y" is a good reason to call the thing 'Y' in the first place. But it's not a good reason to rename it from 'X' to 'Y' if it's already been called 'X' for years. Whether you guys actually understood these mechanisms or not (it's sounding a lot like "not"), *you called it that*, and that name was available for people to express a dependency on. Arbitrarily taking it away again (and needlessly breaking my stuff when I upgrade a system from F26 to F27) is not good.

I know of several codebases in this nexus, actually, because there are a few things people commonly want to do that there is no good Python library to use for. The infamous example is parsing NEVRAs; there was a function for doing this in hawkey, but then someone decided to kill hawkey. So now `rpm` is one of the few not-very-good candidates for doing it.

Note that someone went and built an *entire project* to work around the awkwardness of trying to use this library in real life:

https://github.com/junaruga/rpm-py-installer

**Comment by Conan-Kudo** [comment] 2017-12-22 20:23
> I know of several codebases in this nexus, actually, because there are a few things people commonly want to do that there is no good Python library to use for. The infamous example is parsing NEVRAs; there was a function for doing this in hawkey, but then someone decided to kill hawkey. So now rpm is one of the few not-very-good candidates for doing it.

What? The function should still exist in pyhawkey since libdnf includes all that...

**Comment by AdamWill** [comment] 2017-12-22 20:23
See edit.

**Comment by n3npq** [comment] 2017-12-22 22:20
@AdamWill: Please supply the actual failure mode. Yes Name: is different; it likely doesn't matter (but yes is a change, and is confusing).

Reading on egg-info, I find this statement:

(Note: the pkg_resources module does not automatically look for eggs on PyPI or download them from anywhere; any needed eggs must already be available in a directory on sys.path, or require() will raise a DependencyNotFound error. You can of course trap this error in your code and attempt to find the needed eggs on PyPI or elsewhere. If you want to automatically install dependencies for a project you're working on, you should probably build it using setuptools, which lets you declare dependencies where they can be found by tools like EasyInstall. Setuptools is also needed in order to build eggs.)

So the underlying dependency checking semantic appears to be a module directory on some Python load path.

What appears to be missing is the rpm-python directory (and a symlink may fix; please try.)

Adding 2 egg-info files with different Name: strings might work. Just as easily, you could certainly rewrite your dependencies between F26 -> F27, or just not express the dependency within setup tools; since you are not checking a version in your install.requires file, egg-info files are rather overkill.

*shrug*

**Comment by AdamWill** [comment] 2017-12-22 22:40
No. You're wrong. Really, you're wrong. It's very simple to demonstrate. These are the steps.

    git clone https://pagure.io/fedora-qa/relvalconsumer.git
    cd relvalconsumer
    git checkout 1.1.0
    sudo python setup.py install

Try that with an older `python2-rpm` installed, and it will work. Try it with a recent `python2-rpm` installed, and you will get this:

    Searching for rpm-python
    Reading https://pypi.python.org/simple/rpm-python/
    Couldn't find index page for 'rpm-python' (maybe misspelled?)
    Scanning index of all packages (this may take a while)
    Reading https://pypi.python.org/simple/
    No local packages or working download links found for rpm-python
    error: Could not find suitable distribution for Requirement.parse('rpm-python')

If you then edit the file `install.requires` and change the line `rpm-python` to read `rpm`, the opposite will happen: `sudo python setup.py install` will work with a newer `python2-rpm`, but fail with an older one.

The text you quote doesn't mean what you think it means. It's talking about how `pkg_resources` locates *egg files*, not libraries. It finds all egg files that are located "in a directory on sys.path", and then it reads them. And one of the things it reads out of them is...the name they specify. And it's that name that it uses for dependency resolution purposes. If the name in the egg file is `rpm-python`, then your requirement needs to say `rpm-python`. If the name in the egg file is `rpm`, then your requirement needs to say `rpm`. It doesn't matter at all that the actual Python module that the egg file is for is called `rpm` in both cases. `pkg_resources` does not know or care.

**Comment by AdamWill** [comment] 2017-12-22 22:47
"Adding 2 egg-info files with different Name: strings might work." - yes, it might, but that would be your job, not mine. It's a potential solution to this problem, but you'd need to understand (which you apparently don't right now) exactly what the purpose and meaning of these files is, and the conventions around Python module distribution in general, to know a 'correct' way of setting up your project to build and ship two different eggs that refer to the same actual library.

"Just as easily, you could certainly rewrite your dependencies between F26 -> F27"

No...no, I really can't. I can't even parse quite what you *mean* by this. `relvalconsumer` is just a Python project. It happens to be quite Fedora-specific, but it also happens that it isn't actually packaged for Fedora at all (packaging it would just be a pain in the neck because I'd have to ship updates and all that crap every time I need to tweak the code at all, and it has exactly two production deployments in the world). So there is just...no *place* to implement this difference. I don't have Fedora 26 and Fedora 27 packages for the code. I could theoretically set up two branches of the same code which differ solely in their requirements, and have the ansible plays that deploy the code figure out whether the host is running F26 or F27 and check out the appropriate branch, but that's way the hell out there in crazy-land, and very specific to my situation. I've already resolved my specific situation by just dropping the use of `rpm` entirely in my particular project. But there *could* be other people out there depending on `rpm-python` - as mentioned above, I already found at least one project which has already had to work around this rename.

"or just not express the dependency within setup tools; since you are not checking a version in your install.requires file, egg-info files are rather overkill."

just not expressing the dependency and always assuming it's present would also have worked for my current practical purposes, but again, it's clearly *wrong*, and it doesn't mean that changing the name of the distribution for `pkg_resources` / `setuptools` / etc. purposes was the *right thing to do*. It's clearly a wrong thing to do in general.

**Comment by n3npq** [comment] 2017-12-22 22:47
@AdamWill: if most of what you (or others) need from rpm-python is NEVRA parsing, then just write your own (IMHO).

It's nearly impossible to supply a "standard" and pleasing API in either library or binding API's, and the parsing is Very Not Hard (comparison is of course trickier, but likely has an almost vanishingly small usage case: you, like others, are not specifying a rpm version, nor is there any real need to do so, since rpm specifics change glacially slowly)

**Comment by AdamWill** [comment] 2017-12-22 22:52
Please stop focusing on my specific use case here. The point is, you're providing a library, and its metadata for Python distribution purposes is significant, and it's a really bad idea to just change its name in that metadata purely for purposes of 'neatness' or predictability when you've *already shipped it under the other name* for a long time. You can't possibly know how many people have chosen to use the module and express a dependency on it via some mechanism that uses this metadata, and however many people like that there are, this change inconveniences *all of them*.

But to satisfy your curiosity, as it happens, I was not using `rpm` to parse NEVRAs. My code still uses `hawkey` for that, as it happens. I was using `rpm` to do version comparisons on the parsed NEVRAs, because hawkey's code for doing that was [completely broken for a time](https://github.com/rpm-software-management/libdnf/issues/125). Since that bug's been fixed in hawkey (libdnf) now, I've changed my code back to using hawkey for the version comparison too, which means I can drop the use of `rpm` entirely and not care about this mess. But that only solves the problem for *me*. It doesn't solve it for anyone else who happens to be in the same situation.

**Comment by n3npq** [comment] 2017-12-22 23:43
@AdamWill: If python setup tools and egg-info is actually using Name: strings rather than verifying the a rurally dependency semantic (which is a directory from which a module can be loaded),  I'd professional suggest that python eggs are (in the case of C "libraries" as you have chosen to call bindings) rather deficient.

(aside)
My previous reply -- lost to wifi -- was much sharper and blunter. I did not (and would not and have not) made the change, cannot undo what others have done, and find it difficult to listen to posturing about *two* applications (that are explicitly known) with innuendos that I am clueless or ignorant. Adjust you public behavior as you wish.

Yes that is the sanitized version of my previous ranting post.

**Comment by AdamWill** [comment] 2017-12-23 00:39
OK, let's both calm down a bit. I was just annoyed at running into this entirely unnecessary problem while i was in a hurry last night. I agree that in practical terms it's not a major disaster that's likely to affect lots of people catastrophically. It's still *wrong*, though.

Let's take a second here to dig into naming a bit, because this whole area of nomenclature is kind of a disaster in Python. We're dealing with quite a few sort of overlapping...*things*, here. I've certainly been using 'module' and 'library' a bit sloppily and interchangeably.

Let's start with the easy terms: a module is, as https://packaging.python.org/glossary/#term-import-package puts it, "The basic unit of code reusability in Python". So in your project, `transaction.py` is a single module, which you could load in Python by running `import rpm.transaction`.

One level up from that we have what the glossary calls an "Import Package". If you do `import rpm`, you're loading an "import package". On the filesystem, I'd say these things are part of the "import package" called `rpm`:

    /usr/lib64/python2.7/site-packages/rpm
    /usr/lib64/python2.7/site-packages/rpm/__init__.py
    /usr/lib64/python2.7/site-packages/rpm/_rpm.so
    /usr/lib64/python2.7/site-packages/rpm/_rpmb.so
    /usr/lib64/python2.7/site-packages/rpm/_rpms.so
    /usr/lib64/python2.7/site-packages/rpm/transaction.py

Notably, the `.egg-info` file *IS NOT* part of this "import package". An "import package" *as such* doesn't really contain any packaging 'metadata'. It's just a bunch of Python modules organized in a certain way.

Lastly, we have what the glossary refers to as a ["Built Distribution"](https://packaging.python.org/glossary/#term-built-distribution). When you run `python setup.py build` you're creating one of these "built distributions", and when you run `python setup.py install` you install it. In *your* project, the "built distribution" basically consists of the "import package" plus the `.egg-info` file, but they can potentially contain much more than this - they can contain multiple "import packages" and different modules, 'extra data' files, tons of stuff. (For the record, the term 'library' doesn't really *have* a canonical meaning in this area, but mostly where I've used it above, I really meant "built distribution").

So there's a key point here: the name of your "import package" is 'rpm'. It always has been - before this change, after this change. What's at issue is the name of the "built distribution". Before this change the "built distribution" was called 'rpm-python'. Now it's called 'rpm'.

All the tools we've been talking about - setuptools, pip, tox etc. - deal in "built distributions", not "import packages". If you run, for e.g., `pip install rpm`, you are telling pip "ensure the built distribution named 'rpm' is installed". You are definitely *not* telling it "ensure an import package named 'rpm' is installed". I hope this is clear now and doesn't require further explanation? When you go to pypi, for e.g., and browse around, you're browsing through various "built distributions". By policy of course two "built distributions" registered on pypi can't have the same name, but two "built distributions" registered on pypi *could* potentially install identically-named but quite different "import packages", or modules.

It's easy to get these concepts confused when you're dealing with a relatively simple codebase like this (at least so far as the Python bits are concerned), where there's one "import package" and there's no particular reason why the "built distribution" should have a different name from it. But not *all* codebases are like that. There are quite a few "built distributions" which install *multiple* "import packages". (And by the same token, there are ones that install only a single module, no "import package" at all). Obviously, in this case, the name of the "built distribution" will match at most *one* of the "import packages". It may match none, but it certainly can't simultaneously be the same as *all* of them.

There's also a very common case where the names necessarily differ (and this one really *is* a case where I'd be right behind in saying someone did something stupid here): Python import names are not allowed to have dashes in them, so when you're separating words in the name of a module or "import package", you usually use underscores. However, pypi by policy (it could actually be a rule inherited from one of the underlying tools, I'm not sure...) *does not allow* underscores in the name of "built distributions". So you very commonly find that the pypi "built distribution" for an "import package" with a `_` in its name has a `-` in it instead. I own [one of these](https://pypi.python.org/pypi/resultsdb-conventions) - the "built distribution" is called `resultsdb-conventions`, the "import package" is called `resultsdb_conventions`...

I don't think there's anything fundamentally wrong with this whole setup. "Built distributions" are quite analogous to distribution packages in this system, after all, and we don't allow *those* to have multiple names. I suppose we *do* have the whole `Provides:` mechanism in RPM, though (and equivalent in other distribution packaging systems), which at least AFAIK this system doesn't provide. So you could argue that either that *or* the ability to express dependencies like `requires foo OR bar` is missing.

Finally, just to try (again) to calm things down a bit: I don't intend my suggestion that you don't know all this stuff as a *criticism*. There is a nearly infinite amount of stuff to know about and we all know almost none of it. We're all ragingly ignorant of about 99.9% of all possible human knowledge. :P All I meant to say was, there's quite a lot of background information to know about all these bits, and renaming a "built distribution" is a relatively unusual thing to do that, if you're interested in doing it properly, probably requires some research. For instance, *I* certainly don't know how I'd go about doing that, if I wanted to do it in such a way that things which depended on the old name still worked. I've never done it, so I haven't developed that knowledge. If I were going to do it, the first thing I'd do is go do some more research.

**Comment by AdamWill** [comment] 2017-12-23 00:54
BTW, there's a rather [cryptic bit](https://setuptools.readthedocs.io/en/latest/setuptools.html#metadata) of the setuptools docs that sort of suggests you might be able to use a `provides` kwarg to `setup()`, so we could try something like:

    setup(name='@PACKAGE_NAME@',
    version='@VERSION@',
    provides='rpm-python',
    ...

I've no idea how well that works in practice, though - whether the tools would respect it and so on. I've never tried it, or noticed something that uses it...

**Comment by n3npq** [comment] 2017-12-23 01:08
The key issue here is "What is the failure mode?".

If setup tools is constructing module paths from egg-info Name: directives (which is rather deficient) then there is no solution available (AFAICT) except to feed a Name: directive in some alternative egg-info file.

If Name: is purely informative, then something like a symlink within site-packages might be a sufficient finesse.

Without installing & running Fedora and using strike, its hard to differentiate which of this solutions might "fix" your problem.

BTW, you also need to differentiate between python models (which can be sub-classed), and C=modules like rpm-python (which are sub-typed, not sub-classed).

**Comment by AdamWill** [comment] 2017-12-23 01:15
I'm definitely only talking about Python concepts here. C concepts don't play into all this *at all* since we're only talking about Python ecosystem stuff.

"If setup tools is constructing module paths from egg-info Name: directives (which is rather deficient)"

No, it's not doing that. There is no conceptual connection at any level between the name of the "built distribution" and any filesystem location or name you could pass to `import`. It's purely and simply an identifier for the "built distribution" itself. Just like the name of an RPM package is purely and simply the name of the package: it implies nothing whatsoever about the contents of the package (except by distribution policy).

It's all just like having an rpm package called 'bar' that requires an rpm package called 'foo'. Those are *just* package name identifiers, right? Nothing involved would assume that the rpm package called 'bar' includes a `/usr/bin/bar`, or a `libbar.so`, or a Python module called `bar`, or anything like that. It's just a *name*.

"If Name: is purely informative, then something like a symlink within site-packages might be a sufficient finesse."

This still seems to suggest you're misunderstanding something to me. There is no problem at all with the paths under site-packages, here. The actual site-packages files in RPM 4.13 and RPM 4.14 are all in *exactly the same place*. That's not the part that changed. The part that changed is the name of the "built distribution" - the name that is passed to the `setup()` method as the `name` argument, and that therefore appears in the `.egg-info` file. *That* is what changed. Nothing in the history of humanity has ever looked for anything under `site-packages/rpm-python/`, to be 100% clear, nor has anything ever been located there. That is absolutely not the problem here.

**Comment by n3npq** [comment] 2017-12-23 01:23
If the name isn't used (what I called "informative"), then there should be no difference in loading behavior (unless there is some silly (imho) check on metadata consistency, in which case 2 egg-info files is the only way to deal with what has already been released).

The actual failure mode would provide hints to dig into sources: without the explicit error texts, I can only guess,

**Comment by Conan-Kudo** [comment] 2017-12-23 01:24
@AdamWill The issue that I've been seeing is that people have been putting `rpm` as the setuptools `install_requires`, which obviously never worked before.

In addition, many Linux distributions (RPM-based and not) didn't install the Python bindings via `setup.py` and didn't provide the metadata anyway. That meant that even if you *wanted* to, it wasn't going to work anyway.

While I've been gradually going and fixing this and making sure that packages providing the python bindings actually install via setuptools, I've also encountered enough things and people who expected `pip` to register it as `rpm`, just as CPAN registered `RPM`, `RPM2`, or `RPM4`, and other language bindings also use the `rpm`/`RPM`/`Rpm` name depending on the convention of the ecosystem.

In all honesty, I think this is a correction that needed to happen.

As for Jun's pybindings installer, it was necessary because we refused to publish the bindings to PyPI (see #273). It would have existed regardless of the name in setuptools metadata...

**Comment by n3npq** [comment] 2017-12-23 01:42
If (clueless) users have been putting in "rpm" instead of "rpm-python", then adapting to reality and keeping, rather than reverting, the change seem best imho. It's unclear whether you want "rpm" or reversion to "rpm-Python" based on what you say above.

CPAN is a different culture, irrelevant to python. There are in fact multiple independently developed perl bindings all slowly rotting and unmaintained.

After reading #273, it isn't clear why a egg-info mechanism tied to pypi which isn't being used (by explicitly stated choice) is relevant to this (or any other) rpm issue, further obscuring what you wish to see happen.

**Comment by AdamWill** [comment] 2017-12-23 01:44
@Conan-Kudo Oh, I'm sure *everyone* who tries to express a dependency like this tries the name 'rpm' first. I certainly did. :P But as you say, that never previously did work, so anyone who's previously tried and not just given up when 'rpm' didn't work must surely have landed on 'rpm-python', like I did. Since that's what the name actually *was*. So if you believe that real world people actually have written projects that express this dependency, you implicitly must believe that they wound up writing code that depends on 'rpm-python'...and thus that this change will *break* that code. As I said above, I agree that in theory the name *ought* to be 'rpm'. I'm not saying 'rpm-python' is a better name than 'rpm'. What I'm saying is that once you've already picked a name, changing it isn't a free action.

If you explicitly want to say "we don't think it's worth caring about people who already figured out and used the old name, or people who want to depend on our built distribution in a way that works with both RPM <= 4.13 and RPM >= 4.14", then...I guess fine, but that seems like a pretty 'go away' kinda position. The ideal solution would be to come up with *something* that will allow both 'requires rpm' and 'requires rpm-python' to work. I think there's probably *some* way to do this, I just don't know what it is yet.

**Comment by Conan-Kudo** [comment] 2017-12-23 01:47
> But as you say, that never previously did work, so anyone who's previously tried and not just given up when 'rpm' didn't work must surely have landed on 'rpm-python', like I did.

Actually, what they did was just not specify it at all in setuptools. As I said before, a lot of distributions didn't install the egg data _at all_, so the old name wouldn't work either.

> The ideal solution would be to come up with something that will allow both 'requires rpm' and 'requires rpm-python' to work. I think there's probably some way to do this, I just don't know what it is yet.

I'd be happy to provide a way for the old name to map to the current one, but it seems the Python community believes such a capability is unnecessary...

**Comment by AdamWill** [comment] 2017-12-23 01:49
@n3npq "After reading #273, it isn't clear why a egg-info mechanism tied to pypi"

egg-info isn't "tied to" pypi, just like RPM isn't "tied to" dnf or zypper or yum or Fedora's repositories or SUSE's repositories or Red Hat's repositories.

egg is a "built distribution" format, just like .rpm is a package format. setuptools is a set of tools for producing and working with "built distributions" (and other things), like 'rpm' itself is a set of tools for producing and working with RPM packages. pypi is a repository of built distributions, just like Fedora or RHEL's repositories are repositories of RPM packages. pip is an advanced, dependency-resolving package manager that can retrieve packages from repositories and resolve dependencies between them, like dnf or yum or zypper for RPM packages and repositories.

As I said above, it *is* worth taking into consideration that you've never actually published the built distribution named 'rpm-python' to pypi. It's true that this very likely means far fewer people have interacted with it under that name than would have done if you ever *had* published it to pypi. But by shipping a `setup.py` file which refers to it under that name - which is roughly analogous to shipping a `.spec` file, kinda - you effectively declare the existence of that distribution with that name. Just because you didn't send it to the most widely-used repository of Python distributions doesn't mean it doesn't *exist*.

**Comment by AdamWill** [comment] 2017-12-23 01:51
@Conan-Kudo "Actually, what they did was just not specify it at all in setuptools." - sure, that's what I meant by "just given up when 'rpm' didn't work". I was positing that some obsessive nerds like myself would figure out what the name actually was and use that, while some people would just say 'eh, screw it' and not bother listing the dependency at all. :P

**Comment by n3npq** [comment] 2017-12-23 01:51
FWIW, rpm permits virtual package names, where a Provides: is treated identically to a package NEVR. This was deliberately (and incompletely) ripped out of Obsoletes: in Fedora

**Comment by Conan-Kudo** [comment] 2017-12-23 01:52
@n3npq There's nothing wrong from the RPM point of view. The problem is from the python installed package index for tools like `pip` to process.

**Comment by n3npq** [comment] 2017-12-23 01:59
@AdamWill so there is the problem of what I would call dueling package managers, and it's unclear (particularly because of ever changing incompatibilities in python) what solution(s) should be pursued by rpm.

By all means, use pypi (or apt or ...) if that is what one wishes. Blaming rpm for incompatibilities without making positive (reversion of "rpm" to "rpm-devel" is hardly positive, rather a flip-flop-flip random walk imho) suggestions of what behaviors are desired leads no place useful (to rpm).

**Comment by AdamWill** [comment] 2017-12-23 02:05
I'm sort of reaching the point where I'm thinking it's just not worth trying to explain it any more, especially since apparently trying to bring an RPM analogy into the discussion has only made things *more* confusing, not less. But no, there's no "duelling" going on. I only referred to RPM concepts as an analogy, in the hopes of making all the Python ecosystem bits and levels easier for you to follow. They're not *actually* involved in the practical issue here at all - at no point are the RPM package format or tools at all involved in this.

**Comment by n3npq** [comment] 2017-12-23 02:10
Truly rpm-python should be split off to its own project in the eco system, published to pypi, and whatever else is desired, rather than blaming rpm developers for Newer! Better! Bestest! Python (and depsolvers) changes.

That was the original plan back in 2006 or so, just no round 'tuits.

RPM itself has zero use of Python bindings, and that isn't likely to change any time soon.

**Comment by n3npq** [comment] 2017-12-23 02:14
@AdamWill I fail to see how 2 names is better than one, particularly since there seems to be no already implemented mechanism within egg-info to deal with multiple names (and the claim afaict is that the functionality is deemed unnecessary).

**Comment by n3npq** [comment] 2017-12-23 02:29
Correction: PEP 345 appears to have a Provides-Dist: tag to handle virtual packages bundled together. Using existing functionality wisely (assuming implemented) would seem to be the best way forward.

Providing two egg-info files to handle the change seems rather hacks.

**Comment by AdamWill** [comment] 2017-12-23 21:27
"rather than blaming rpm developers for Newer! Better! Bestest! Python (and depsolvers) changes."

Python didn't *change* anything here. rpm did: the name in the `setup.py` you ship. That's it. That's the extent of the change that caused the problem. I'm still baffled as to why it seems so hard to explain this, but I know @Conan-Kudo and I are on the same page, so maybe it's best if just he and I try and figure something out and submit a PR.

I already pointed out the 'Provides-Dist' tag. The problem is I'm not sure if setuptools, which is the "built distribution"-handling tool that just about everyone uses these days (the only other extant alternative is the original distutils, which still works for very simple cases), actually implements it. As I said, AFAICT PEP 345 was written with the intent that it would be implemented by a project called distutils2, which was supposed to sort of obsolete both the original distutils and setuptools, but that never happened, the project was abandoned. setuptools remained the de facto 'standard' tool, but I'm not sure that it ever actually implemented all the bits of PEP 345.

**Comment by pmatilai** [comment] 2018-01-03 14:31
Here's my 5c from the POV that I'm the one who came up with the original -python suffix:

Adding the separate setup.py had to do with the idea/intention of splitting the python bindings into a separate repo/tarball, in which case the tarball probably would've been called rpm-python. That of course never happened but the setup.py remained, largely forgotten for many years. Anyway, that's the background from which the -python suffix in the module name comes from, and I can assure you that not much thought was applied when selecting it, it's just *something* to put in there.

The way I see it, the original rpm-python name is wrong because it doesn't match the actual module name, so this is a *fix*, not just a random rename. But then I really didn't expect anybody to be actually using that value for anything at all. Me, I'd rather fix the name in Fedora 26 too and move on. Or if we really can't survive that transition then lets just revert the flipping commit already. This just isn't worth this much noise, really.

**Comment by ignatenkobrain** [comment] 2018-01-03 15:00
I think everyone should really switch to `rpm` from `rpm-python` (or even to not rely on it because rpm is not published on PyPI). My 5czk.

**Comment by Conan-Kudo** [comment] 2018-01-03 15:13
> Me, I'd rather fix the name in Fedora 26 too and move on.

I'm okay with this, but I think it's fine to just Let The Past Die(TM) and with RPM 4.14 onward, we'll have the right name.

**Comment by AdamWill** [comment] 2018-01-03 17:16
@pmatilai we were already done with the noise before more people started chipping in =)

I was rather assuming that *RHEL* has also been shipping the `.egg` files, meaning that the `rpm-python` name will be baked into RHEL 7 and thus around at least somewhere for God knows how long, unless we can convince whoever packages rpm for RHEL to switch the name. Though I admit I haven't actually verified that. If it's only Fedora that's ever shipped the `.egg` file, then yeah, given that only relatively few people probably ever bothered to use the name, it'd probably be okay to just change it in F26.

I still think the best option is to just have RPM provide *both* names, though, if we can actually find a reasonable way of doing that. I haven't looked at it yet because of the RH holiday shutdown, I barely touched a computer for the last two weeks.

**Comment by pmatilai** [comment] 2018-01-04 08:33
No existing RHEL version uses setup.py to build rpm's python bindings, that's only done in Fedora. So no rpm .egg in RHEL.

**Comment by Conan-Kudo** [comment] 2018-01-04 13:10
And until I changed it for openSUSE, it was never had the egg either. And that's being introduced in openSUSE with v4.14. So, new name only.

**Comment by AdamWill** [comment] 2018-01-04 21:13
Aha, that's good to know. So in that case maybe we really could just change the name in F26. Or say that it's not worth caring about enough to fix since it'll only matter during F26's lifetime anyway.

**Comment by pmatilai** [comment] 2018-02-12 11:33
Okay so I think we can safely conclude no action needed upstream, closing. We can discuss the Fedora side in Fedora BZ if it's necessary, but I'd really just rather leave it alone there too.

**Closed by pmatilai** 2018-02-12 11:33 UTC
