### ISSUE TITLE
The --noprep option executes %mkbuilddir which breaks %generate_buildrequires in Mock

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/rpm#3120] opened 2024-05-22 13:31 UTC
I hit this accidentally with `rpm-build-4.19.91-1.fc41.x86_64` (not yet build in Rawhide, or already untagged, not sure). Happened to me when I was reproducing [FTBFS against a Copr project that contained that pre-release version](https://bugzilla.redhat.com/show_bug.cgi?id=2279987).

Mock runs, at when all the dynamic build deps are resolved and installed, `rpmbuild --noprep ...`, just to not necessarily re-do the same (potentially expensive) step again.  The problem is that `--noprep` still executes the `%mkbuilddir`:

```
+ umask 022
+ cd /builddir/build/BUILD/argparse-manpage-4.5-build
+ test -d /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/rm -rf /builddir/build/BUILD/argparse-manpage-4.5-build
...
```

So the `argparse-manpage-4.5-build` directory is removed, but not recreated, because `--noprep`.

**To Reproduce**

Use the pre-release 4.19.91 version of RPM in mock chroot to build any package with %generate_buildrequires.

```
copr mock-config @python/python3.13 fedora-rawhide-x86_64 > /tmp/python3.13.cfg
mock -r /tmp/python3.13.cfg package-using-generate-buildrequires.src.rpm
```
You need [Mock v5.3+](https://rpm-software-management.github.io/mock/Release-Notes-5.3) that has this optimization.

**Expected behavior**

The `rpmbuild --noprep` shouldn't execute `%mkbuilddir`?  Have a new option `--nomkbuilddir`?  I'm not sure.

**Output**

```
setting SOURCE_DATE_EPOCH=1716336000
Executing(%mkbuilddir): /bin/sh -e /var/tmp/rpm-tmp.J1UIqb
+ umask 022
+ cd /builddir/build/BUILD/argparse-manpage-4.5-build
+ test -d /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/rm -rf /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/mkdir -p /builddir/build/BUILD/argparse-manpage-4.5-build
+ /usr/bin/mkdir -p /builddir/build/BUILD/argparse-manpage-4.5-build/SPECPARTS
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%generate_buildrequires): /bin/sh -e /var/tmp/rpm-tmp.AMDAIv
+ umask 022
+ cd /builddir/build/BUILD/argparse-manpage-4.5-build
+ cd argparse-manpage-4.5
/var/tmp/rpm-tmp.AMDAIv: line 34: cd: argparse-manpage-4.5: No such file or directory

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.AMDAIv (%generate_buildrequires)
```

**Environment**
 - OS / Distribution: Fedora 40, Fedora Rawhide in-chroot
 - Version: 4.19.1.1-1 on host, 4.19.91-1.fc41 in-chroot

**Comment by praiskup** [comment] 2024-05-22 13:32
Corresponding [line-in-Mock-code](https://github.com/rpm-software-management/mock/blob/3986df1555780b76811b5aa1c199429ee8b09cc0/mock/py/mockbuild/backend.py#L792).

**Comment by hroncok** [comment] 2024-05-22 14:16
> You need [Mock v5.3+](https://rpm-software-management.github.io/mock/Release-Notes-5.3) that has this optimization.

Even before that, `--noprep` was used for the last rpmbuild round, so I assume even older mock would be impacted.

> (not yet build in Rawhide, or already untagged, not sure).

Not yet built. It was built in Python 3.13 copr when pushed to distgit. In the meantime, I have removed the build.

**Comment by pmatilai** [comment] 2024-05-23 03:41
My first reaction to this is: "we have --noprep? :flushed: "
I mean, in my 20+ years of life around rpm I must've seen that option *somewhere* but I had absolutely norecollection it existed. Much less that anybody would be using it.

I can see why mock would use such a thing, but I'm not really comfortable with that because it seems that mock is now driving the build and not rpmbuild. And this means any changes to rpmbuild are even more difficult than they are otherwise.

That said, I'm not exactly surprised that %mkbuilddir breaks *something* because it is quite a big change. Lets see what we can do about it, on the outset --noprep disabling %mkbuilddir seems reasonable but I'm only halfway into my first coffee...

**Comment by pmatilai** [comment] 2024-05-23 03:45
One takeaway from this is that we need some tests that mimick what mock does.

**Comment by pmatilai** [comment] 2024-05-23 03:53
Okay #3121 has closer details + reproducer info, closing this as a dupe despite being the earlier one.

**Closed by pmatilai** 2024-05-23 03:53 UTC
