### ISSUE TITLE
rpm --whatrequires does not resolve provides

### ISSUE THREAD

**Issue by mikhailnov** [rpm-software-management/rpm#1426] opened 2020-11-07 17:59 UTC
There is a package which requires "java-devel":
```
$ rpm -qR wildfly | grep ^java
java-devel >= 1:1.7
```

The package which provides it is the following:
```
$ rpm -q --whatprovides java-devel
java-1.8.0-openjdk-devel-1.8.0.252.b02-0.0.ea.x86_64
```

Now I want to find out why `java-1.8.0-openjdk-devel` was installed and make a query:
```
$ rpm -q --whatrequires java-1.8.0-openjdk-devel
no package requires java-1.8.0-openjdk-devel
```

But:
```
$ rpm -q --whatrequires java-devel
wildfly-10.1.0-14.noarch
```

I expected to see `wildfly` in the output of `rpm -q --whatrequires java-1.8.0-openjdk-devel`. Is it a bug or a feature?

RPM is 4.16.0:
```
user@ROSA-Nickel ~ $ rpm -q rpm
rpm-4.16.0-6.x86_64
```

**Comment by pmatilai** [comment] 2020-11-09 06:41
```
       --whatrequires CAPABILITY
              Query  all packages that require CAPABILITY for proper functioning.
```

It's literally as it says, it only looks for packages that require the queried *capability*. This is expected behavior and not a bug, although resolving the capability would be a nice option to have. In the meantime, `rpm -e --test` can be used as a workaround.

**Closed by pmatilai** 2020-11-09 06:41 UTC

**Comment by mikhailnov** [comment] 2020-11-09 07:06
Thanks!
