### ISSUE TITLE
%license (and similar tags) should take priority over other listings and RPM shouldn't warn about files listed twice

### ISSUE THREAD

**Issue by torsava** [rpm-software-management/rpm#2144] opened 2022-08-04 11:46 UTC
Hi,
I believe RPM is behaving in a confusing way in the `%files` section.

For example, when you have a Python project you usually list in the `%files` section the entire directory under the Python `site-packages`. E.g. for `pipenv` we list the entire directory `%{python3_sitelib}/pipenv` (evaluates to e.g. `/usr/lib64/python3.10/site-packages/pipenv`). This is standard practice and widely followed. However, oftentimes you want to also tag some of those files using a special macro, such as `%license`, so that for example bundled license files are properly listed in the metadata.

However, if you do this, RPM currently complains that the files are listed twice, and also it's not guaranteed that the `%license` listing will win over the regular listing, it seems to be just implementation detail, which doesn't work for some other special macros.

I've encountered this in my PR: https://src.fedoraproject.org/rpms/pipenv/pull-request/54

**Comment by hroncok** [comment] 2022-08-05 09:40
We have talked about this with @torsava and I feel like the explanation here is a bit hard to understand, so let me try some examples:

We'd like the following examples:

```
%files
/foo/bar
%license /foo/bar/baz/LICENSE
```

```
%files
/foo/bar
%doc /foo/bar/baz/howto.txt
```

```
%files
/foo/bar
%lang(cs) /foo/bar/langs/cs.frr
```

and similar directives to: 

 - Not warn about the file listed twice
 - Ensure the marker (license, doc, etc.) is applied¹

The alternative is tedious:

```
%files
%dir /foo/bar
/foo/bar/<all the files except baz listed manually>
%dir /foo/bar/baz
/foo/bar/baz/<all the files except LICENSE listed manually>
%license /foo/bar/baz/LICENSE
```

-------------------

¹ From experience, I can tell that this is *almost always* true but I have seen a situation where it was not the case.

**Comment by pmatilai** [comment] 2022-08-09 07:07
This is a dupe of #336.

**Closed by pmatilai** 2022-08-09 07:07 UTC
