### ISSUE TITLE
Could not build rpm from master branch with cmake -  No package 'libmagic' found

### ISSUE THREAD

**Issue by rhabacker** [rpm-software-management/rpm#2452] opened 2023-03-24 10:30 UTC
I'm trying to build rpm from master branch on openSUSE 15.4 and got a build failure:

```` 
cd ~
git clone https://github.com/rpm-software-management/rpm.git
$ cmake -S rpm -B rpm-build
-- The C compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")  
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Performing Test Iconv_IS_BUILT_IN
-- Performing Test Iconv_IS_BUILT_IN - Success
-- Found Iconv: built in to C library  
-- Checking for module 'lua>=5.2'
--   Found lua, version 5.3.6
-- Checking for module 'popt'
--   Found popt, version 1.16
-- Checking for module 'libmagic'
--   No package 'libmagic' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:138 (pkg_check_modules)
``` 

The problem is that there is no pkgconfig support for `libmagic` provided by the associated `file-devel` package:
```
$ rpm -q -l file-devel
/usr/include/magic.h
/usr/lib64/libmagic.so
/usr/share/doc/packages/file-devel
/usr/share/doc/packages/file-devel/AUTHORS
/usr/share/doc/packages/file-devel/ChangeLog
/usr/share/doc/packages/file-devel/NEWS
/usr/share/doc/packages/file-devel/README
/usr/share/licenses/file-devel
/usr/share/licenses/file-devel/COPYING
/usr/share/man/man3/libmagic.3.gz
```

**Comment by pmatilai** [comment] 2023-03-24 11:05
Yup, this is a dupe of #2246

**Closed by pmatilai** 2023-03-24 11:05 UTC
