### ISSUE TITLE
rpmdb --exportdb does not work on read-only fs

### ISSUE THREAD

**Issue by lnussel** [rpm-software-management/rpm#1266] opened 2020-06-10 11:45 UTC
rpmdb --exportdb calls rpmtxnBegin() with RPMTXN_READ flags. Internally that function calls rpmlockNew() and rpmlockAcquire(). Neither function has a flags parameter to specify what kind of lock is requested. rpmlockNew() automatically creates a read lock if it can't open the .rpm.lock file in RW mode. rpmlockAcquire() however wants to establish a write lock always so won't work on a  read-only lock.

So in the end it means that means rpmdb --exportdb only works as root on a read-write file system. Doesn't work for unprivileged users, nor on read only file systems. That doesn't seem to be intentional given the rpmlockNew() fallback to a read lock.

**Comment by pmatilai** [comment] 2020-08-13 10:22
I agree --exportdb should work on read-only fs. Unprivileged user is a different matter, we can't really let unprivileged user to block system updates through ro-locking.

**Comment by JetXujing** [comment] 2022-12-01 03:43
Is there any solution to fix the problem? If not, can we consider adding information description in rpm?

**Comment by pmatilai** [comment] 2024-10-11 11:06
Closing as a duplicate of #3371 - nothing wrong with this ticket except that it's just not syncing to our internal tracker and can't afford to get stuck on that just now. Apologies for the noise.

**Closed by pmatilai** 2024-10-11 11:06 UTC
Labels: bug
