### ISSUE TITLE
RFE: Convenient version comparison macro

### ISSUE THREAD

**Issue by hroncok** [rpm-software-management/rpm#1217] opened 2020-05-13 20:47 UTC
Hello. I had a recent discussion with @Conan-Kudo about version comparison in spec conditionals.

https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/message/467NMLL3DTRZQBEX5LPFU6ZD5P56SSF3/

So I dug a bit and found the excellent `rpm.vercmp()` Lua function. Unfortunatelly, using this in spec seems a bit complicated:

```spec
%if %{lua:print(rpm.vercmp(rpm.expand("%python3_version"), "3.9"))} >= 0
```

Hence, I was thinking there might be a `%vercmp` convenient macro.

It could either just expose the Lua function:

```spec
%if %{vercmp %{python3_version} 3.9} >= 0
```

However, while at it, it could be even more clever:

```spec
%if %{vercmp %{python3_version} >= 3.9}
```

I have come up with this, which is not very nice code, but it gets the job done apparently:

```lua
%vercmp() %{lua:
local first = rpm.expand("%1")
local op = rpm.expand("%2")
local second = rpm.expand("%3")
if (first == "%1") or (op == "%2") or (second == "%3") then
    rpm.expand("%{error:%%vercmp needs three argument}")
end
if not (op:match("^[<>=!]?=$") or op:match("^[<>=]$")) then
    rpm.expand("%{error:%%vercmp second argument must be a comparison operator}")
end
local cmp = rpm.vercmp(first, second)
print(((cmp == 0 and op:match("^[<>=]?=$")) or (cmp == -1 and op:match("<=?")) or
      (cmp == 1 and op:match(">=?"))or (cmp ~= 0 and op == "!=")) and 1 or 0)
}
```

So I was wondering whether such macro could be added to the standard macro selection. If this is not the place, I'll offer it to redhat-rpm-config macros.

**Comment by pmatilai** [comment] 2020-05-14 07:32
This is closely related to, but perhaps not a duplicate of #897.

Having an actually usable version comparison macro is one of the rare things that truly are generic enough to belong to rpm, it's actually rather hysterical how little we have in that space.

This being rpm, versions are the primary numerical entities we deal with, and as such could easily warrant something a bit special. I'm myself wondering if we could somehow expose the version comparison in our expression parser - as we now can do things like
```
$ rpm --eval "%[0<1]"
1
```
...it'd seem fitting to be able to do this with same ease with EVRs too. I don't have any concrete suggestions offhand though. @mlschroe ?

**Comment by pmatilai** [comment] 2020-05-14 08:12
...except that versions are not integers, they're strings, and the expression parser now explicitly separates the two. So we could make the string comparison *be* version comparison, at which point you could do this in a spec

```
%if "%{python3_version}" >= "3.9"
...
%endif
```

...and it'd do the actually right thing without any extra macros, but also available in the macro side through %[] and %{expr:...}.

**Comment by hroncok** [comment] 2020-05-14 08:15
OTOH this is backwards incompatible and a bit weird.

What if `""` would still compare strings, but without `""` would compare versions? That is backwards compatible with comparing integers.

**Comment by pmatilai** [comment] 2020-05-14 08:30
We can't really hijack integers because we support simple mathematical operations on them besides just comparison, and might be some other technical restrictions. In any case, string comparisons in specs typically are either == or !=, in which case treating them as versions wouldn't affect the outcome. And looking at Fedora specs, there are numerous examples where people actually use just that (apparently oblivious to it not doing what they expect):

```
%if "%{php_version}" < "5.6"
%if "%(pkg-config --version 2>/dev/null)" < "0.20.0"
%if "%{version}" > "2.12"
%if "%{_qt5_version}" < "5.12.0"
%if "%version" < "0.20"
%if 0%{?rhel} && "%rhel" < "5"
```

**Comment by hroncok** [comment] 2020-05-14 08:32
right. ok then, comparing `""` as stings works for me \o/ Obviously, that'll be 4.16+ only, so in Fedora terms, rawhide+.

**Comment by pmatilai** [comment] 2020-05-14 08:37
Yeah - right now would actually be the optimal time to implement this as there are some other incompatibilities in the 4.16 expression parser as well, and the macro side of this is all new now, so there's not that much that is incompatible. 

There are some technical obstacles though, for example rpmvercmp() and a higher level version parsing/comparison (which isn't really exported at all) needing moving to librpmio from librpm. Hmm.

**Comment by pmatilai** [comment] 2020-05-14 08:47
Hmm. The other hmm is that rpmvercmp() can actually return 0 for strings that are very obviously different (#925), which can get decidedly weird.

**Comment by hroncok** [comment] 2020-05-14 08:51
also "01" == "1"

**Comment by pmatilai** [comment] 2020-05-14 09:17
Yeah... might get too weird really. Another, saner option might be using single quotes (or similar) to denote rpm version strings over regular strings.

**Comment by hroncok** [comment] 2020-05-14 09:51
So, here are couple examples. I haven't checked if they don't collide with existing syntax.

```spec
# int comparison, fallbacks to version comparison if at least one operand has nondigits?
%if %{php_version} < 5.6

# string comparison, produces incorrect results some time
%if "%{php_version}" < "5.6"

# single quotes (easy, but it doesn't actually scream *this is version comparison*)
%if '%{php_version}' < '5.6'

# backticks (easy, as above, but at least screams "I am special")
%if `%{php_version}` < `5.6`

# string prefixes (see Python f-strings, b-strings and r-strings; confusing to non-Python people)
%if v"%{php_version}" < v"5.6"

# square brackets (special enough, but screams "I am an array with 1 element" to me)
%if [%{php_version}] < [5.6]

# square brackets  around the whole thing (why? screams "wtf")
%if [%{php_version} < 5.6]

# special %if like %ifarch (maybe too much?)
%ifver %{php_version} < 5.6

# a prefix without quotes (both confusing)
%if @%{php_version} < @5.6
%if $%{php_version} < $5.6

# a special macro (easy to understand a bit more complicated to write) 
%if %{vercmp %{php_version} < 5.6}

# a special macro to mark the values as versions (a bit more complicated to write as well)
%if %{ver:%{php_version}} < %{ver:5.6}

# golging the above (a bit more complicated to read)
%if %{V:%{php_version}} < %{V:5.6}
```

**Comment by hroncok** [comment] 2020-05-14 09:55
Sorted my favorite things:

```
%if %{php_version} < 5.6
%if `%{php_version}` < `5.6`
%if %{ver:%{php_version}} < %{ver:5.6}
%if %{vercmp %{php_version} < 5.6}
%ifver %{php_version} < 5.6
```

**Comment by ffesti** [comment] 2020-05-14 09:59
Another option would be having special operators. But this is also confusion as we use the normal `<`,  `>`, ... in dependencies. I also don't have a good suggestion. `%if %{php_version} ver>= "1.2.3"` looks weird, too. But may be someone has an better idea.

**Comment by pmatilai** [comment] 2020-05-14 11:45
Yup, the way the expression parser works there are basically two possibilities: either tag the version strings or the comparison operator, somehow. I think the former is the far less weird option.

@ does ensure the reader attention more than any of the quoting variants:
`@1.2 < @1.0` 
`@1.2@ < @1.0@`

Another "easy" special marker would be # but that seems entirely wrong for the purpose.
`#1.2 < #1.0`

**Comment by hroncok** [comment] 2020-05-14 13:52
While `@1.2@ < @1.0@` looks quite OK, when combined with macros, it's not very readable either:

```spec
%if @%{php_version}@ < @5.6@
```

**Comment by pmatilai** [comment] 2020-05-14 14:08
> v"%{php_version}" < v"5.6"

I initially failed to register the Python connection. I kinda like it as it's a far stronger hint at what it is than the other variants, and has precedent in at least one major language.

**Comment by voxik** [comment] 2020-05-15 09:27
I don't understand how the discussion come from something reasonably nice and expressive which is within current RPM functionality such as `%if %{vercmp %{python3_version} >= 3.9}` to proposing something weird such as `@1.2@ < @1.0@`

**Comment by pmatilai** [comment] 2020-05-15 10:37
It's not just a matter of what's nice, it's to a large degree also a question of what's technically possible and available.

The quest at hand is to find the most reasonable syntax to identify strings as versions at the most fundamental level of the "rpm language" which is the expression parser, now living like half a level below the macro engine. Within this realm, the v"1.2" syntax might well the best of the choices sor far.  But whatever the selected syntax for that, it doesn't *exclude* building more user-friendly stuff on top, on the contrary it's an *enabler*, and hopefully nice enough to be usable as-is.

**Comment by pmatilai** [comment] 2020-05-15 11:08
To further elaborate on that, if deemed necessary/useful, a macro primitive such as %{V:...} could be added for *converting to* the expression syntax. Eg assuming the proposed pythonisque syntax, %{V:1.2} would simply expand to v"1.2" which the expression parser would then understand as a native element. Rpm users might indeed be more at home with the macro-oriented syntax.

**Closed** 2020-05-27 12:42 UTC
