### ISSUE TITLE
Change in behaviour from 4.14 to 4.15 when calling rpmbuild --nobuild

### ISSUE THREAD

**Issue by zazaho** [rpm-software-management/rpm#875] opened 2019-09-30 15:56 UTC
I noticed a change in the functioning of rpmbuild with the option --nobuild activated. I use this option to check the spec file but also to check unsatisfied build dependencies. In the previous version "rpmbuild --nobuild" would check the build requirements but not in version 4.15.

I have looked at the code and perhaps it might be an option to add -bd, -td and -rd to call only the doCheckBuildRequires subroutine.

Thank you for considering this.

**Comment by pmatilai** [comment] 2019-10-02 09:45
It does smell like a regression, but then it's not clear whether --nobuild was ever intended to be used stand-alone. By appearance more like a disabler similar to --nocheck and --noprep etc, to be used with some other build modes. Eg 'rpmbuild -bb --nobuild <spec>' does still work for checking buildrequires, and should work in older versions too.

Anyway, I dont think such a change was *intended* either, so it deserves to be looked atl.

**Comment by ffesti** [comment] 2019-11-13 16:50
OK, the behaviour of 4.14 is rather crude:
```
rpmbuild --nobuild ~/rpmbuild/SPECS/test.spec 
error: Failed build dependencies:
	foobar is needed by test-1-1.fc30.x86_64
```
`rpmbuild ~/rpmbuild/SPECS/test.spec` has no output
`rpmbuild --bs --nobuild ~/rpmbuild/SPECS/test.spec` has no output

```
./rpmbuild --bb --nobuild ~/rpmbuild/SPECS/test.spec 
error: Failed build dependencies:
	foobar is needed by test-1-1.fc30.x86_64
```
The last command works with 4.15, too. So while this is a change in behaviour I would argue that 4.15 behaves more consistently by not doing more when adding `--nobuild`. Is there any reason you can't use `--bb --nobuild`? Yes, it is kinda weird to tell rpmbuild to do abuild and then not to build but that's what get's the test run...

**Comment by zazaho** [comment] 2019-11-13 17:05
Hi Florian,

Thank you for looking into this.

Let me explain the use-case of how I used this "option" before. I have a 
script that sometimes check upstream websites for some software that I 
rely on and that I have custom build to enable options that fedora may 
not enable by default. If some new packages become available I want to run 
a batch build job during the night to compile all new packages.

Something like:
for s in *.spec
do
 rpmbuild --clean -ba $s ||:
done

I used the rpmbuild --nobuild "feature" as a quick check to make sure that 
all build dependencies for all packages are met without doing any actual 
building.

With the change from 4.14 -> 4.15 this no longer worked as before. I can 
see that there are alternatives like "-bb --nobuild". I think my 
suggestion is actually quite clean for my use-case: an option that only 
runs the check build-deps part of the logic.

I hope this makes sense.

With kind regards,

Sacha

**Comment by ffesti** [comment] 2019-11-14 07:50
I am hesitant to add even more build modes if the desired mode of operation can already be achieved with existing options. I just checked and `rpmbuild --nobuild -ba $s` also works. So running the same command once with --nobuild and - if everything is fine - then without should just do what you want.

I am wondering if calling rpmbuild without one of the build mode options should actually be made an error and should display the usage.

**Comment by pmatilai** [comment] 2019-11-14 07:53
At least --rmspec and --rmsource are documented as being usable standalone. Not that I can see why on earth would anybody ever want to do "rpmbuild --rmspec foo.spec" but maybe that's just me.

**Comment by pmatilai** [comment] 2019-11-14 08:01
> rpmbuild -bs --nobuild ~/rpmbuild/SPECS/test.spec has no output

That's because we explicitly disable buildrequires checking for source packaging. Which isn't right because the spec might be unparseable without its buildrequires but...

**Comment by ffesti** [comment] 2019-11-18 10:13
Ok, as there is a supported way of doing this already I am just closing this.
Adding a new top level command that does the same thing only would add to the confusion and create even more weird interactions with all the different parameters.

**Closed by ffesti** 2019-11-18 10:13 UTC

**Comment by pmatilai** [comment] 2019-11-18 10:34
Right, I'll add a remark to 4.15.0 release notes about it then to make it official behavior change.
