### ISSUE TITLE
debugedit.c patches

### ISSUE THREAD

**Issue by n3npq** [rpm-software-management/rpm#171] opened 2017-03-05 17:09 UTC
rpm5.org carries this patch from Yocto:
      https://patchwork.openembedded.org/patch/46887
which likely should be added when updating debug edit.c soon.

**Comment by n3npq** [comment] 2017-03-05 17:48
For rpm portability with older versions of elfutils, this harmless sanity check might be useful:

(excuse the different hash functions in use in the patch snippet below)
@@ -1533,40 +1493,12 @@
   /* Now format the build ID bits in hex to print out.  */
   {   
     const uint8_t * id = (uint8_t *)build_id->d_buf + build_id_offset;
-    char hex[build_id_size * 2 + 1];
-    int n = snprintf (hex, 3, "%02" PRIx8, id[0]);
-    assert (n == 2);
-    for (i = 1; i < (int)build_id_size; ++i)
-      {
-       n = snprintf (&hex[i * 2], 3, "%02" PRIx8, id[i]);
-       assert (n == 2);
-      }
+    char *hex = pgpHexStr(id, build_id_size);
     puts (hex);
+    free(hex);
   }   
 }
 
-/* It avoided the segment fault while file's bss offset have a large number.
-   See https://bugzilla.redhat.com/show_bug.cgi?id=1019707
-       https://bugzilla.redhat.com/show_bug.cgi?id=1020842 for detail. */
-void valid_file(int fd)
-{
-  Elf *elf = elf_begin (fd, ELF_C_RDWR, NULL);
-  if (elf == NULL)
-  {
-    error (1, 0, "elf_begin: %s", elf_errmsg (-1));
-    return;
-  }
-
-  elf_flagelf (elf, ELF_C_SET, ELF_F_LAYOUT);
-    
-  if (elf_update (elf, ELF_C_WRITE) < 0)
-    error (1, 0, "elf_update: %s", elf_errmsg (-1));
-
-  elf_end (elf);
-
-  return;
-}
-
 int        
 main (int argc, char *argv[])
 {
@@ -1682,9 +1614,6 @@
       exit (1);
     }
            
-  /* Make sure the file is valid. */
-  valid_file(fd);
-
   dso = fdopen_dso (fd, file);
   if (dso == NULL)
     exit (1);

**Comment by n3npq** [comment] 2017-03-05 17:58
Portability of debugedit.c on systems that do not support #include <dwarf.h> (solaris, *BSD) can be achieved by duplicating certain DWARF standard constants:

-#ifndef EM_AARCH64
-#define EM_AARCH64      183             /* ARM AARCH64 */
-#endif
-#ifndef R_AARCH64_ABS32
-#define R_AARCH64_ABS32 258
-#endif 
-
-/* some defines taken from the dwarf standard */
-
-#define DW_TAG_compile_unit    0x11
-
-#define DW_AT_name             0x03
-#define DW_AT_stmt_list                0x10
-#define DW_AT_comp_dir         0x1b
-
-#define DW_FORM_addr           0x01
-#define DW_FORM_block2         0x03
-#define DW_FORM_block4         0x04
-#define DW_FORM_data2          0x05
-#define DW_FORM_data4          0x06
-#define DW_FORM_data8          0x07
-#define DW_FORM_string         0x08
-#define DW_FORM_block          0x09
-#define DW_FORM_block1         0x0a
-#define DW_FORM_data1          0x0b
-#define DW_FORM_flag           0x0c
-#define DW_FORM_sdata          0x0d
-#define DW_FORM_strp           0x0e
-#define DW_FORM_udata          0x0f
-#define DW_FORM_ref_addr       0x10
-#define DW_FORM_ref1           0x11
-#define DW_FORM_ref2           0x12
-#define DW_FORM_ref4           0x13
-#define DW_FORM_ref8           0x14
-#define DW_FORM_ref_udata      0x15
-#define DW_FORM_indirect       0x16

**Comment by n3npq** [comment] 2017-03-05 18:00
debugedit.c --help can be improved (and potentially internationalized)

*shrug*

@@ -1323,16 +1290,15 @@

 static struct poptOption optionsTable[] = {
   { "base-dir",  'b', POPT_ARG_STRING, &base_dir, 0,
-    N_("base build DIRECTORY of objects"), N_("DIRECTORY") },
+      "base build directory of objects", NULL },
   { "dest-dir",  'd', POPT_ARG_STRING, &dest_dir, 0,
-    N_("DIRECTORY to rewrite base-dir into"), N_("DIRECTORY") },
+      "directory to rewrite base-dir into", NULL },
   { "list-file",  'l', POPT_ARG_STRING, &list_file, 0,
-    N_("FILE where to put list of source and header file names"), N_("FILE") },
+      "file where to put list of source and header file names", NULL },
   { "build-id",  'i', POPT_ARG_NONE, &do_build_id, 0,
-    N_("recompute build-id note and print on stdout"), NULL },
+      "recompute build ID note and print ID on stdout", NULL },
   { "build-id-seed", 's', POPT_ARG_STRING, &build_id_seed, 0,
-    N_("if recomputing the build-id note, use this string as hash SEED"), N_("SEED") },
-
+      "if recomputing the build ID note use this string as hash seed", NULL },
     POPT_AUTOHELP
   { NULL, 0, 0, NULL, 0, NULL, NULL }
 };

**Comment by Conan-Kudo** [comment] 2017-03-06 05:04
@n3npq For what it's worth, to make it all unformatted text, use ` ``` ` at the top of the block, and ` ``` `  at the bottom of the block. That way, it looks like patches or code. :)

In addition, you can tell it to be diff style by doing ` ```diff ` for the top of the block.

**Comment by rpm-maint** [comment] 2017-03-06 13:11
On Sun, 2017-03-05 at 09:09 -0800, Jeff Johnson wrote:
> rpm5.org carries this patch from Yocto:
>       https://patchwork.openembedded.org/patch/46887
> which likely should be added when updating debug edit.c soon.

It is slightly hard to review a patch to a patch.
Could you extract the precise patch you suggest would be helpful and
post it to rpm-maint for review?

Also I suspect that the latest patch that moved away from using
ELF_C_RDWR_MMAP makes the original problem also go away.

Thanks,

Mark

**Comment by rpm-maint** [comment] 2017-03-06 13:24
On Sun, 2017-03-05 at 09:48 -0800, Jeff Johnson wrote:
> For rpm portability with older versions of elfutils, this harmless sanity check might be useful:
> 
> (excuse the different hash functions in use in the patch snippet below)
> @@ -1533,40 +1493,12 @@
>    /* Now format the build ID bits in hex to print out.  */
>    {   
>      const uint8_t * id = (uint8_t *)build_id->d_buf + build_id_offset;
> -    char hex[build_id_size * 2 + 1];
> -    int n = snprintf (hex, 3, "%02" PRIx8, id[0]);
> -    assert (n == 2);
> -    for (i = 1; i < (int)build_id_size; ++i)
> -      {
> -       n = snprintf (&hex[i * 2], 3, "%02" PRIx8, id[i]);
> -       assert (n == 2);
> -      }
> +    char *hex = pgpHexStr(id, build_id_size);
>      puts (hex);
> +    free(hex);
>    }   
>  }

I don't understand this hunk. What is it attempting to do?

Also I assume you posted the reverse patch?

> -/* It avoided the segment fault while file's bss offset have a large number.
> -   See https://bugzilla.redhat.com/show_bug.cgi?id=1019707
> -       https://bugzilla.redhat.com/show_bug.cgi?id=1020842 for detail. */

This is indeed a bug in elfutils, fixed in elfutils 0.162.
But also only occurs for bogus/bad ELF files in the first place.

> -void valid_file(int fd)
> -{
> -  Elf *elf = elf_begin (fd, ELF_C_RDWR, NULL);
> -  if (elf == NULL)
> -  {
> -    error (1, 0, "elf_begin: %s", elf_errmsg (-1));
> -    return;
> -  }
> -
> -  elf_flagelf (elf, ELF_C_SET, ELF_F_LAYOUT);
> -    
> -  if (elf_update (elf, ELF_C_WRITE) < 0)
> -    error (1, 0, "elf_update: %s", elf_errmsg (-1));
> -
> -  elf_end (elf);
> -
> -  return;
> -}

So this opens and closes the ELF file and tries to write it out to disk,
but since nothing changed all this does is make libelf do a layout check
of all headers. Where it would notice nothing changed, so ELF_C_WRITE
would not actually write something out. Except if it does see a
discrepancy and might "correct" a header field. It sounds slightly safer
to do an ELF_C_UPDATE so that nothing might accidentally be written out.

Although it might indeed catch the issue with the bogus ELF file earlier
(and so prevent a crash with a buggy elfutils) I am not sure it is
really the task of rpm/debugedit to make sure the user doesn't have
bogus/bad ELF files and/or an old/buggy libelf implementation. But if
you don't mind opening/closing/reading the ELF file twice this might
indeed not be that expensive (compared to all the other work debugedit
does). It is somewhat bogus and obscure though.

Cheers,

Mark

**Comment by rpm-maint** [comment] 2017-03-06 13:31
On Sun, 2017-03-05 at 09:58 -0800, Jeff Johnson wrote:
> Portability of debugedit.c on systems that do not support #include
> <dwarf.h> (solaris, *BSD) can be achieved by duplicating certain DWARF
> standard constants:

I think you reversed the patch you are proposing again.
I'll leave it to others to say whether it makes sense or if rpm should
just require up to date elf.h and dwarf.h headers be present.

Cheers,

Mark

**Comment by n3npq** [comment] 2017-03-06 17:10
Yes all the patches were reversed.

Meanwhile I just sorted the first patch with Mark Hatle (aka "fray"). The segfault is not reproducible with EU-0.168.

The hex printing was an attempt to avoid pgpHexStr() which differs between rpm.org and rpm5.org.

You explained away the valid_file() check

The other changes to debugedit --help are largely cosmetic. I maintain POPT and so am slightly OCD ;-)

**Comment by mhatle** [comment] 2017-03-06 17:12
Re: https://patchwork.openembedded.org/patch/46887

The bug and related information are available at:

https://bugzilla.yoctoproject.org/show_bug.cgi?id=4089

I am currently working through this to see if the current rpm (4) version suffers from the same failure.  I will update this if it does or does not.

**Comment by n3npq** [comment] 2017-03-06 17:26
Another issue that might make debugedit.c more portable is similar to inlining DW_FORM* instead of
`#include <dwarf.h>`

Instead of using EU version dependent #defines for strtab_init() etc (which needs -lebl), it may be more "portable" to just inline the routines and maintain a copy in debugedit.c.

That would permit non-elfutils -lelf to be used "portably" even if there is code duplication.

I dunno (yet) how much code would need to be duplicated, but will take a look soonishly.

**Comment by mhatle** [comment] 2017-03-07 14:39
I have tested the current rpm4 debugedit within the Yocto Project environment -without- the patch, with the known binary doing cross-compiled work (little to big endian) and have not been able to reproduce the issue.

Either debugedit has had a tweak over the years or elfutils has had a bug fixed.  (The original defect being resolved by this patch set was related to the "shdr.sh_type" being in the binary endian, not the running system endian.)

So it appears there is no need for the specific patch related: https://patchwork.openembedded.org/patch/46887

**Comment by pmatilai** [comment] 2017-03-08 13:06
MJW also says not needed, closing.

**Closed by pmatilai** 2017-03-08 13:06 UTC
