### ISSUE TITLE
RFE: Add tag for source/patch checksums

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/rpm#1126] opened 2020-03-20 13:31 UTC
In Fedora, Mageia, OpenMandriva, and other distributions, we often work around the fact that sources and patches cannot be verified by having some kind of extra file where sources have checksums (`sources`, `sha1.lst`, `.abf.yml`, etc.).

This is annoying and problematic, as it makes this inconsistent and adds extra external scaffolding when unnecessary. Additionally, because we don't have a way to specify these things in the RPM spec itself, we can't have RPM auto-download sources from URLs and verify that the sources downloaded are correct. Per the comment in the macros.in file:

```rpm-spec
#
# Should rpm try to download missing sources at build-time?
# Enabling this is dangerous as long as rpm has no means to validate
# the integrity of the download with a digest or signature.
%_disable_source_fetch 1
```

In Fedora, we're considering having sources auto-fetched and uploaded to the lookaside cache as part of accepting PRs for package updates, but to make this straightforward, we'd want this to be in the spec file so that we know we're downloading what we're supposed to.

Something along the lines of `SourceN(<checksum-type>): <checksum-hash>` (and similar for `PatchN`, of course) was what I'm thinking of.

There's some prior art here in other package management solutions that influenced this idea. For example, Arch and Alpine both let you specify a source URL and specify checksums to validate this, as does Solus' ypkg YAML format.

For example, [the Arch PKGBUILD for `rpm-tools`](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rpm-tools) has the following snippet:

```shell
source=(http://ftp.rpm.org/releases/rpm-$_base_pkgver/rpm-$pkgver.tar.bz2
	rpmextract.sh
        rpmlib-filesystem-check.patch)
sha256sums=('ddef45f9601cd12042edfc9b6e37efcca32814e1e0f4bb8682d08144a3e2d230'
            '3e5bf450d4628366ba35469ec0530a99cd09ab2616a3d261a3f68270f481f777'
            'bd0e6dbd458f990268c60324190c6825b234647ecdde08296d2b453dc4bce27a')
```

And [Solus' ypkg YAML for `rpm`](https://dev.getsol.us/source/rpm/browse/master/package.yml) does something similar:

```yaml
source     :
- https://github.com/rpm-software-management/rpm/archive/rpm-4.14.2.1-release.tar.gz : 92cab9da7524cf4e4abf33f160cdfb9e63fe021bc7133f97735f70cdec777400
```

I realize that there might be some complication here for adding it for `%sourcelist` and `%patchlist`, but hopefully this gives enough of an idea of what is desired to satisfy this request.

**Comment by Conan-Kudo** [comment] 2020-03-20 13:32
(cc: @pypingou, @nphilipp, @praiskup)

**Comment by pmatilai** [comment] 2020-03-20 13:46
This is a dupe of #463

**Comment by Conan-Kudo** [comment] 2020-03-20 13:47
Welp, sucks to be me for not finding that...

**Closed** 2020-03-20 13:50 UTC
