### ISSUE TITLE
Since beta2 introducing // mode, some files are not removable during %clean

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm#1289] opened 2020-06-24 09:08 UTC
Since beta2 introducing parallel mode, some files are not removable.
See build*.log at http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20200623141813.tv.duvel.19852/log/rpm-4.16.0-0.beta2.1.mga8/
(…)

Wrote: /home/iurt/rpmbuild/RPMS/noarch/rpm-apidocs-4.16.0-0.beta2.1.mga8.noarch.rpm
Executing(%clean): /bin/sh -e /home/iurt/rpmbuild/tmp/rpm-tmp.ClaJkJ
+ umask 022
+ cd /home/iurt/rpmbuild/BUILD
+ cd rpm-4.16.0-beta2
+ /usr/bin/rm -rf /home/iurt/rpmbuild/BUILDROOT/rpm-4.16.0-0.beta2.1.mga8.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(--clean): /bin/sh -e /home/iurt/rpmbuild/tmp/rpm-tmp.RZOwSI
+ umask 022
+ cd /home/iurt/rpmbuild/BUILD
+ rm -rf rpm-4.16.0-beta2
rm: cannot remove 'rpm-4.16.0-beta2/tests/testing/data/misc/hello.payload': Permission denied
rm: cannot remove 'rpm-4.16.0-beta2/tests/testing/data/misc/hello.intro': Permission denied
rm: cannot remove 'rpm-4.16.0-beta2/tests/testing/data/macros.testfile': Permission denied
rm: cannot remove 'rpm-4.16.0-beta2/tests/testing/data/SOURCES/hello-1.0-modernize.patch': Permission denied
rm: cannot remove 'rpm-4.16.0-beta2/tests/testing/data/SOURCES/bar.c': Permission denied

This didn't happen in my prior local build, so I guess it depends on umask.
I "fixed" it with "chmod -R +w tests/testing/":
http://svnweb.mageia.org/packages/cauldron/rpm/current/SPECS/rpm.spec?r1=1598795&r2=1598794&pathrev=1598795

**Comment by soig** [comment] 2020-06-24 09:23
Actually with beta3, I can reproduce it locally:
$ LC_ALL=C rm -fr BUILD/rpm-4.16.0-beta3/
(…)
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/data/SPECS/test-subpackages-pathpostfixes.spec': Permission denied
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/data/SPECS/ifmultiline.spec': Permission denied
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/data/SPECS/flangtest.spec': Permission denied
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/data/misc/hello.intro': Permission denied
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/data/misc/hello.payload': Permission denied
rm: cannot remove 'BUILD/rpm-4.16.0-beta3/tests/testing/bin': Permission denied

**Comment by pmatilai** [comment] 2021-01-15 13:31
Closing as duplicate of #1382 - this was first, but the latter ended up with more info.

**Closed by pmatilai** 2021-01-15 13:31 UTC
