### ISSUE TITLE
rpmsign --signfiles is broken on master

### ISSUE THREAD

**Issue by dashea** [rpm-software-management/rpm#723] opened 2019-05-30 17:55 UTC
signFile() in sign/rpmsignfiles.c creates an array of zeroes (https://github.com/rpm-software-management/rpm/blob/master/sign/rpmsignfiles.c#L44) and then passes those zeroes unmodified as the input to imv-evm-util's sign_hash() (https://github.com/rpm-software-management/rpm/blob/master/sign/rpmsignfiles.c#L53). The values stored in RPMSIGTAG_FILESIGNATURES are thus all signatures of 32 zeroes (or whatever the hash length is if not sha256).

8f8fe718413a4066ecc6718f92091d9e87a2d443 removed the code that filled digest with the converted contents of fdigest.

**Comment by pmatilai** [comment] 2019-06-04 08:59
The point of that commit is that those digests are already in the desired binary format inside the file objects, so there's no need to do it again. AFAICS the problem is that it's still passing digest and diglen to sign_hash() when it should pass fdigest instead:

```
--- a/sign/rpmsignfiles.c
+++ b/sign/rpmsignfiles.c
@@ -50,7 +50,7 @@ const char *key, char *keypass, uint32_t *siglenp)
     signature[0] = '\x03';
 
     /* calculate file signature */
-    siglen = sign_hash(algo, digest, diglen, key, keypass, signature+1);
+    siglen = sign_hash(algo, fdigest, diglen, key, keypass, signature+1);
     if (siglen < 0) {
        rpmlog(RPMLOG_ERR, _("sign_hash failed\n"));
        return NULL;
```

If you can try the above "patch", great, but even better would be a full reproducer procedure, starting from scratch (key creation and all) so we can try creating a proper testcase to avoid future regressions. I know I managed to set *something* up at some point in time, but I never was convinced I was doing the right thing and here we are...

**Comment by pmatilai** [comment] 2019-06-04 09:02
Oh and thanks for spotting and reporting, shipping regressions is never nice.

**Comment by pmatilai** [comment] 2019-06-04 10:19
Should be fixed in PR #734 , but I'd still appreciate if you can verify, and also for a full reproducer, like said I'm not at all convinced I'm doing the right thing with these tools.

**Comment by dashea** [comment] 2019-06-04 17:12
https://gist.github.com/dashea/ffe49cb5703d3e44870d71006bfeedd0 is a script that will create an rpm and all of the necessary keys, run rpmsign --signfiles, and verify the results. I ran it against https://github.com/rpm-software-management/rpm/pull/734 and the signature is correct.

**Closed** 2019-06-05 07:33 UTC
Labels: REGRESSION

**Comment by pmatilai** [comment] 2019-06-05 07:35
Thanks for verifying, and for the script! I'll try to make a test-case out of that as time permits.
