### ISSUE TITLE
sb in lhs and rhs

### ISSUE THREAD

**Issue by newrow** [rpm-software-management/rpm#3185] opened 2024-06-26 08:16 UTC
https://github.com/rpm-software-management/rpm/blob/c00d8a0ed32169baf82cd0a34ffd1c9377b09c38/lib/rpmvs.c#L443

https://github.com/rpm-software-management/rpm/blob/c00d8a0ed32169baf82cd0a34ffd1c9377b09c38/lib/rpmvs.c#L445

both operands are sb

I guess it should be like

    sb->* - sa->*

**Comment by ffesti** [comment] 2024-07-19 10:12
OK, turn out we have an older ticket for this also: #1057

**Comment by pmatilai** [comment] 2024-07-29 08:02
Closing as duplicate of #1057

**Closed by pmatilai** 2024-07-29 08:02 UTC
Labels: bug
