### ISSUE TITLE
invalid OpenPGP signature with Sequoia for existing RPM

### ISSUE THREAD

**Issue by davide125** [rpm-software-management/rpm#2351] opened 2023-01-13 16:20 UTC
I have a number of RPMs that work fine on Fedora 37, but fail to validate on Rawhide and ELN with `package tag 268: invalid OpenPGP signature`:

```
# rpm -qip fb-genchefserverlist-20230113-032842.x86_64.rpm 
error: fb-genchefserverlist-20230113-032842.x86_64.rpm: Header RSA signature: BAD (package tag 268: invalid OpenPGP signature)
error: fb-genchefserverlist-20230113-032842.x86_64.rpm: not an rpm package (or package manifest)
```

I can privately share a copy of the impacted RPM if needed (and will work on crafting a minimal repro I can publish publicly). In the meantime, here's the full trace output:

```
# RPM_TRACE=1 rpm -qip fb-genchefserverlist-20230113-032842.x86_64.rpm 
_rpmInitCrypto: entered
_rpmInitCrypto: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f681258660
_rpmDigestInit: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f681247c00
_rpmDigestInit: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681258660
_rpmDigestUpdate: data: &[] <- 0x7fcc89c82c78
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x7fcc89c82c78
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681258660
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc090
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc090
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681258660
_rpmDigestUpdate: data: &[] <- 0x55f681245de0
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x55f681245de0
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681258660
_rpmDigestUpdate: data: &[] <- 0x55f681245f40
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x55f681245f40
_rpmDigestUpdate: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681258660
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681258660
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681247c00
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681247c00
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681258660
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681247c00
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bbfa8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bbfb0
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f6812480b0
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681247c00
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bbfa8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bbfb0
_rpmDigestFinal: -> success
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681258660
_rpmDigestFinal: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f6812480b0
_rpmDigestFinal: -> success
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpPubkeyKeyID: entered
_pgpPubkeyKeyID: pkt: &[] <- 0x55f6812471d0
_pgpPubkeyKeyID: Key ID: 809A8D7CEB10B464
_pgpPubkeyKeyID: keyid: &[] <- 0x7fff4b6bc130
_pgpPubkeyKeyID: -> success
_pgpPrtParams: entered
_pgpPrtParams: pkts: &[] <- 0x55f6812471d0
_pgpPrtParams: paramsp: &mut <- 0x7fff4b6bc128
_pgpPrtParams: PgpDigParams { obj, signid: buffer, userid: userid }: returning 0x55f6812037d0
_pgpPrtParams: -> success
_pgpPrtParamsSubkeys: entered
_pgpPrtParamsSubkeys: pkts: &[] <- 0x55f681249bf0
_pgpPrtParamsSubkeys: subkeys: &mut <- 0x7fff4b6bc130
_pgpPrtParamsSubkeys: subkeys_count: &mut <- 0x7fff4b6bc12c
_pgpPrtParamsSubkeys: Got 0 subkeys
_pgpPrtParamsSubkeys: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f681247c00
_rpmDigestInit: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f68124a570
_rpmDigestInit: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x7fcc89c82c78
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68124a570
_rpmDigestUpdate: data: &[] <- 0x7fcc89c82c78
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc090
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68124a570
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc090
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x55f681245de0
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68124a570
_rpmDigestUpdate: data: &[] <- 0x55f681245de0
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681247c00
_rpmDigestUpdate: data: &[] <- 0x55f681245f40
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68124a570
_rpmDigestUpdate: data: &[] <- 0x55f681245f40
_rpmDigestUpdate: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681247c00
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681247c00
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f68124a570
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68124a570
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681247c00
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68124a570
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bbfa8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bbfb0
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681249960
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68124a570
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bbfa8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bbfb0
_rpmDigestFinal: -> success
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681247c00
_rpmDigestFinal: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681249960
_rpmDigestFinal: -> success
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpPubkeyKeyID: entered
_pgpPubkeyKeyID: pkt: &[] <- 0x55f68127a5d0
_pgpPubkeyKeyID: Key ID: F55AD3FB5323552A
_pgpPubkeyKeyID: keyid: &[] <- 0x7fff4b6bc130
_pgpPubkeyKeyID: -> success
_pgpPrtParams: entered
_pgpPrtParams: pkts: &[] <- 0x55f68127a5d0
_pgpPrtParams: paramsp: &mut <- 0x7fff4b6bc128
_pgpPrtParams: PgpDigParams { obj, signid: buffer, userid: userid }: returning 0x55f6811e32c0
_pgpPrtParams: -> success
_pgpPrtParamsSubkeys: entered
_pgpPrtParamsSubkeys: pkts: &[] <- 0x55f68127b9b0
_pgpPrtParamsSubkeys: subkeys: &mut <- 0x7fff4b6bc130
_pgpPrtParamsSubkeys: subkeys_count: &mut <- 0x7fff4b6bc12c
_pgpPrtParamsSubkeys: Got 0 subkeys
_pgpPrtParamsSubkeys: -> success
_pgpPrtParams: entered
_pgpPrtParams: pkts: &[] <- 0x55f68127e0f8
_pgpPrtParams: paramsp: &mut <- 0x55f68127d128
_pgpPrtParams: -> error: Failure: Signature Packet
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f68127b710
_rpmDigestInit: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x55f681248740
_rpmDigestInit: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68127b710
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc170
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681248740
_rpmDigestUpdate: data: &[] <- 0x7fff4b6bc170
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f68127b710
_rpmDigestUpdate: data: &[] <- 0x55f68127f1a8
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x55f681248740
_rpmDigestUpdate: data: &[] <- 0x55f68127f1a8
_rpmDigestUpdate: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f68127b710
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68127b710
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f681248740
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681248740
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f68127ad70
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681248740
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bc1e8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bc1f0
_rpmDigestFinal: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x55f68127b730
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f681248740
_rpmDigestFinal: datap: Option<&mut> <- 0x7fff4b6bc1e8
_rpmDigestFinal: lenp: Option<&mut> <- 0x7fff4b6bc1f0
_rpmDigestFinal: -> success
error: fb-genchefserverlist-20230113-032842.x86_64.rpm: Header RSA signature: BAD (package tag 268: invalid OpenPGP signature)
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68127ad70
_rpmDigestFinal: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x55f68127b730
_rpmDigestFinal: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
_rpmDigestFinal: entered
_rpmDigestFinal: -> error: Failure: ctx must not be NULL
error: fb-genchefserverlist-20230113-032842.x86_64.rpm: not an rpm package (or package manifest)
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_pgpDigParamsFree: entered
_pgpDigParamsFree: -> success
_rpmFreeCrypto: entered
_rpmFreeCrypto: -> success
#
```

**Comment by davide125** [comment] 2023-01-13 16:45
Put up a minimal package that repros the issue at http://dcavalca.fedorapeople.org/fb-test-opengpg-20230113-083251.x86_64.rpm

**Comment by nwalfield** [comment] 2023-01-13 17:28
I extracted the signature and looked at it:

```
$ sq packet dump --hex /tmp/blob.pgp 
Unknown or Unsupported Packet, new CTB, 3 header bytes + 284 bytes
    Tag: Signature Packet
    Error: Malformed MPI: leading bit is not set: expected bit 8 to be set in  1000000 (40)
  
    00000000  c2                                                 CTB
    00000001     c0 5c                                           length
    00000003           04                                        version
    00000004              00                                     type
    00000005                 01                                  pk_algo
    00000006                    08                               hash_algo
    00000007                       00  10                        hashed_area_len
    00000009                              05                     subpacket length
    0000000a                                 02                  subpacket tag
    0000000b                                    63 c1 88 71      sig creation time
    0000000f                                                09   subpacket length
    00000010  10                                                 subpacket tag
    00000011     11 12 0f 47 14 e5 6d  c8                        issuer
    00000019                              00 00                  unhashed_area_len
    0000001b                                    f6               digest_prefix1
    0000001c                                       50            digest_prefix2
    0000001d                                          08 00 40                ..@
    00000020  7b a4 e3 f0 bc 27 b1 e2  1c f2 1a af e7 0e 67 27   {....'........g'
    00000030  b2 6d fc 01 df dc 56 f5  1e 53 08 2c 33 7c f3 b1   .m....V..S.,3|..
    00000040  de 05 b7 55 41 6e 8c b4  82 99 5d 01 8c 74 93 05   ...UAn....]..t..
    00000050  f8 0a 3d aa 23 f2 8c a5  0e 91 d8 32 e2 ae 10 fd   ..=.#......2....
    00000060  33 41 bc 97 dc 21 81 7e  e9 31 9c 27 5c da 81 df   3A...!.~.1.'\...
    00000070  df 1e 32 ca 61 30 7d b2  28 89 e9 2e 85 c5 4e e4   ..2.a0}.(.....N.
    00000080  df 7d 82 bd bb d6 58 73  a3 3d 44 65 f2 5d 99 34   .}....Xs.=De.].4
    00000090  2d 24 af 63 ac 64 4d a8  19 62 9a 5d c6 30 5c a5   -$.c.dM..b.].0\.
    000000a0  80 cb ed 12 a1 7d f8 cb  fc ee fe f1 74 3b 4d 84   .....}......t;M.
    000000b0  8d 7f 3a af 85 a4 ac 7f  fc 8f a8 f5 ce a7 69 7a   .:..........iz
    000000c0  35 c8 60 c8 0e fd 0d 0a  9b fa d3 77 1d 7a 19 aa   5.`........w.z..
    000000d0  02 55 6f 32 87 15 d3 b7  14 ba cc 42 51 06 4a fd   .Uo2.......BQ.J.
    000000e0  f5 40 30 31 1b d8 4d c5  7b a5 00 6b 87 06 ca 1b   .@01..M.{..k....
    000000f0  61 64 b9 b3 c5 9c 79 f2  a1 59 83 ae e3 2c b2 e0   ad....y..Y...,..
    00000100  f8 22 cf 3a cb ae 82 48  5d 14 4e f2 f2 19 98 aa   .".:...H].N.....
    00000110  66 d3 80 63 02 b8 28 f5  45 73 a2 ed 85 79 bd      f..c..(.Es...y.
  
```

The MPIs appear to be malformed, and Sequoia is quite strict in what it accepts.  What implementation are you using to sign the rpm?

**Comment by nwalfield** [comment] 2023-01-13 17:30
The signature for those interested:

```
-----BEGIN PGP ARMORED FILE-----

wsBcBAABCAAQBQJjwYhxCRAREg9HFOVtyAAA9lAIAEB7pOPwvCex4hzyGq/nDmcn
sm38Ad/cVvUeUwgsM3zzsd4Ft1VBboy0gpldAYx0kwX4Cj2qI/KMpQ6R2DLirhD9
M0G8l9whgX7pMZwnXNqB398eMsphMH2yKInpLoXFTuTffYK9u9ZYc6M9RGXyXZk0
LSSvY6xkTagZYppdxjBcpYDL7RKhffjL/O7+8XQ7TYSNfzqvhaSsf/yPqPXOp2l6
NchgyA79DQqb+tN3HXoZqgJVbzKHFdO3FLrMQlEGSv31QDAxG9hNxXulAGuHBsob
YWS5s8WcefKhWYOu4yyy4PgizzrLroJIXRRO8vIZmKpm04BjArgo9UVzou2Feb0=
=fu/M
-----END PGP ARMORED FILE-----
```

**Comment by davide125** [comment] 2023-01-13 18:03
> What implementation are you using to sign the rpm?

It's an internal implementation (that from what I can tell uses gpg under the hood, but I need to double check). I will followup with the engineers that developed it and see what we can find out. Thanks for the quick reply!

**Comment by nwalfield** [comment] 2023-01-13 18:34
Thanks!

**Comment by nwalfield** [comment] 2023-01-13 18:58
This issue might be related: https://github.com/community/community/discussions/27607

**Comment by pmatilai** [comment] 2023-01-16 10:23
Right, this basically looks like something to document in #2346.

**Comment by nwalfield** [comment] 2023-01-16 11:00
@teythoon pointed out that GnuPG does not generate New format CTBs, so this was likely not generated by GnuPG.  This is typical behavior for gocrypt, which is [documented as not being conformant](https://github.com/sylabs/golang-x-crypto/commit/374053ea96cb300f8671b8d3b07edeeb06e203b4#diff-47e53358306da9dcb5ca7dd110d31067d11f231fc3baed4f51e4026e26b521bfL506).

**Comment by nwalfield** [comment] 2023-01-16 13:06
@pmatilai: Yup.  My comment was more directed towards @davide125: it would be good to confirm that this is the bug that I think it is.

**Comment by chantra** [comment] 2023-01-18 02:14
I was hoping this could be reported to go crypto and possibly fix, as reading the comment in code felt more like "This break the RFC,  but happens to work, so let's do it.", but then I stumble on https://github.com/golang/go/issues/44226 which deprecates go-crypto.

**Comment by pmatilai** [comment] 2023-01-18 06:52
Heh, from that ticket:
> OpenPGP is not something we want Go developers to use.

Based on the intentional RFC break, that seems to go beyond just Go developers...

**Comment by nwalfield** [comment] 2023-01-18 07:38
> I was hoping this could be reported to go crypto and possibly fix, as reading the comment in code felt more like "This break the RFC, but happens to work, so let's do it.", but then I stumble on [golang/go#44226](https://github.com/golang/go/issues/44226) which deprecates go-crypto.

The OpenPGP implementation was broken out of go-crypto by Proton, which they continue to maintain and develop as [gopenpgp](https://github.com/ProtonMail/gopenpgp).

**Comment by nwalfield** [comment] 2023-01-18 07:41
> I was hoping this could be reported to go crypto and possibly fix, as reading the comment in code felt more like "This break the RFC, but happens to work, so let's do it.", but then I stumble on [golang/go#44226](https://github.com/golang/go/issues/44226) which deprecates go-crypto.

Also, thanks for the link to that issue.  I hadn't read it yet.

**Comment by davide125** [comment] 2023-02-28 21:11
To close the loop on this, we were able to fix our internal implementation by switching to https://github.com/ProtonMail/go-crypto which includes a fix for this (see https://github.com/ProtonMail/go-crypto/commit/d3d8a14a4d4f772c205a10c24d14676522ee95d2).

**Comment by nwalfield** [comment] 2023-03-01 07:37
@davide125 : Thanks for following up and confirming that this was not a bug in rpm or rpm-sequoia.

**Comment by pmatilai** [comment] 2023-03-02 11:56
Okay, lets close the issue then. Thanks everybody.

**Closed by pmatilai** 2023-03-02 11:56 UTC

**Comment by fche** [comment] 2023-08-11 13:27
Please at least suppress this diagnostic then.  There is nothing a user can do about the situation, so it's not worth bothering him or her about it.

**Comment by catvin82** [comment] 2023-08-14 23:02
Intel OneAPI is causing this now, I have no idea why or how to fix. F38 and I cannot update my system or uninstall oneapi

**Comment by mathieu-aubin** [comment] 2023-10-22 22:00
> Intel OneAPI is causing this now, I have no idea why or how to fix. F38 and I cannot update my system or uninstall oneapi

`rpm -e --nosignature package.name`

**Comment by Cyborgscode** [comment] 2023-12-02 11:41
Any Updates here, as it still happens on Fedora 38 .

**Comment by pmatilai** [comment] 2023-12-04 07:39
There's nothing to update here, because this is not a bug in rpm. As the message says, the issue is a malformed signature in some packages, and the upstreams of such packages should be notified to allow them to fix their signing.

The trick to get rid of them is to note the `h#` number from the error message, query for that with `rpm -q --nosignature <number>` to get the package name and then `rpm -e --nosignature <name>` it. 

Or `rpm -e --nosignature $(rpm --nosignature --querybynumber <number>` will get rid of it in one go, but then you'll miss what package it actually was.

**Comment by pmatilai** [comment] 2023-12-04 08:01
That said... this seems common enough that it could be a candidate for handling as NOTTRUSTED content to allow upgrading out of the situation. @nwalfield , thoughts?

**Comment by nwalfield** [comment] 2023-12-04 08:19
As I understand it `NOTTRUSTED` means that we've verified the signature, but it uses e.g. a weak algorithm and hence cannot be fully relied upon.  These signatures and keys are out of spec and although Sequoia detects them, it does not correct them.  As such it is non-trivial to check the signatures in which case `NOTTRUSTED` does not seem appropriate.

Or, am I misunderstand the semantics of `NOTTRUSTED`?

**Comment by pmatilai** [comment] 2023-12-04 08:35
Heh, you have a far more clear idea of what NOTTRUSTED is than I do. I seem to have thinking of it it as a carpet we can sweep all this "used to accept but no longer do" material under :sweat_smile: but the reality is more subtle than that. So, never mind the NOTTUSTED idea then, you're right.

**Comment by fche** [comment] 2023-12-04 11:18
> As the message says, the issue is a malformed signature in some packages, and the upstreams of such packages should be notified to allow them to fix their signing.

That's fine for the long term, but does not help users with these formerly acceptable packages **already installed**.  The tooling does not make it easy to identify, let alone remove or update them.

**Comment by Cyborgscode** [comment] 2023-12-04 14:19
It would be a great help, if the illsigned package was named when the warnings show up.

**Comment by pmatilai** [comment] 2023-12-12 11:29
It only works if you actually follow the instructions. Look more carefully.

**Comment by pkitszel** [comment] 2024-03-07 11:48
> Intel OneAPI is causing this now, I have no idea why or how to fix. F38 and I cannot update my system or uninstall oneapi

I have just noticed this problem, but for other software packaged by Intel. In my case customers could not ignore signatures, as that is crucial for the scenario. (Code is easy to build and install manually, but customers want Secure Boot).

As I'm an Intel employee, I will report the issue to our internal signing service/tool.

**Comment by Cyborgscode** [comment] 2024-03-07 12:45
> It only works if you actually follow the instructions. Look more carefully.

Yeap, my fault.. 

$ rpm -q --nosignature --querybynumber 306
intel-conda-index-tool-19.1.0-166-19.1.0-166.x86_64

another intel package..

**Comment by Cyborgscode** [comment] 2024-03-07 12:49
$ rpm -q --nosignature --querybynumber 306
intel-conda-index-tool-19.1.0-166-19.1.0-166.x86_64
$ rpm -q --nosignature --querybynumber 307
intel-tbb-libs-2020.0-166-2020.0-166.x86_64
$ rpm -q --nosignature --querybynumber 308
intel-conda-tbb-linux-64-shadow-package-2020.0-166-2020.0-166.x86_64
$ rpm -q --nosignature --querybynumber 309
intel-conda-intel-openmp-linux-64-shadow-package-19.1.0-166-19.1.0-166.x86_64
$ rpm -q --nosignature --querybynumber 311
intel-openmp-19.1.0-166-19.1.0-166.x86_64
$ rpm -q --nosignature --querybynumber 312
intel-mkl-doc-ps-2020-2020.4-304.noarch
$ rpm -q --nosignature --querybynumber 313
intel-mkl-doc-2020-2020.4-304.noarch
$ rpm -q --nosignature --querybynumber 314
intel-comp-l-all-vars-19.1.0-166-19.1.0-166.noarch
$ rpm -q --nosignature --querybynumber 315
intel-comp-nomcu-vars-19.1.0-166-19.1.0-166.noarch
$ rpm -q --nosignature --querybynumber 316
intel-mkl-common-2020.0-166-2020.0-166.noarch
$ rpm -q --nosignature --querybynumber 317
intel-mkl-common-c-2020.0-166-2020.0-166.noarch
$ rpm -q --nosignature --querybynumber 321
intel-conda-mkl-include-linux-64-shadow-package-2020.0-166-2020.0-166.x86_64

and the intel list does on and on in Fedora.

**Comment by Cyborgscode** [comment] 2024-03-07 12:52
BTW...

]$ rpm -qi intel-conda-intel-openmp-linux-64-shadow-package-19.1.0-166
Fehler: rpmdbNextIterator: wird übersprungen h#     309 
Header RSA Signatur: BAD (Header tag 268: invalid OpenPGP signature: Parsing an OpenPGP packet:
  Failed to parse Signature Packet
      because: Signature appears to be created by a non-conformant OpenPGP implementation, see <https://github.com/rpm-software-management/rpm/issues/2351>.
      because: Malformed MPI: leading bit is not set: expected bit 8 to be set in     1011 (b))
Header SHA1 Prüfsumme: OK
Das Paket intel-conda-intel-openmp-linux-64-shadow-package-19.1.0-166 ist nicht installiert


"SHA1" ? hasn't that been deprecated and is now disabled in most distros?

**Comment by mhitza** [comment] 2024-06-11 19:43
I'm seeing similar issues when I try to upgrade F39 to F40, and the packages involved

```
~ » rpm -q --nosignature --querybynumber 12128
intel-psxe-common-2020.0-088-2020.0-088.noarch
                                                                                                                      
~ » rpm -q --nosignature --querybynumber 12124
intel-conda-mkl-static-linux-64-shadow-package-2020.0-166-2020.0-166.x86_64
                                                                                                                      
~ » rpm -q --nosignature --querybynumber 12103
intel-conda-mkl-include-linux-64-shadow-package-2020.0-166-2020.0-166.x86_64
                                                                                                                      
~ » rpm -q --nosignature --querybynumber 12091
intel-conda-intel-openmp-linux-64-shadow-package-19.1.0-166-19.1.0-166.x86_64
                                                                                                                      
~ » rpm -q --nosignature --querybynumber 12090
intel-conda-tbb-linux-64-shadow-package-2020.0-166-2020.0-166.x86_64
```

**Comment by pkitszel** [comment] 2024-06-18 14:00
Intel has already a solution for that for some time. Each package needs a rebuild though (and a new version number assigned of course).

**Comment by arekm** [comment] 2025-02-19 14:41
> but does not help users with these formerly acceptable packages **already installed**. 

I have packages, built and signed by (earlier) rpm software, installed and these packages no longer exist as *.rpm files. New rpm complains about pgp signatures and ignores these installed packages.

Saying "it's not a bug in rpm" doesn't help as it was a bug in earlier rpm (right?) and new rpm+sequoia doesn't accept what old rpm produced.  In kernel terms that would be similar to "breaking userspace".

rpm -e uninstalls things, so that's not a option.

Is there a way to remove signatures from local rpm db for such packages, so rpm will treat these as unsigned? (and hopefully won't complain, just these packages won't be verifiable - not sure if that would work this way though).

Or re-sign packages in local rpm db with own key?

Some better solution should exist than "try to find packages and reinstall, we wish you luck".
