### ISSUE TITLE
Document all tags

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/rpm#1384] opened 2020-10-06 19:13 UTC
There is a lot feature in rpm which has literally no other documentation than source code:
 OrderWithRequires
 %artifact
 %readme
 VCS
 meta
 and a very likely a bunch of others.
 
I believe that all of this and actually every feature, tag, or modifier in available in the SPEC file should be documented on the rpm.org site.

**Comment by pmatilai** [comment] 2020-10-07 05:23
Nobody will disagree.

The problem is that there's a mountain of undocumented stuff in the last twenty years, and that there's no place to put new stuff into. For example, documenting %artifact would essentially writing docs on *all* %files features first to have a meaningful place to put it into. That just doesn't happen, and hence this limbo goes on.

**Comment by pmatilai** [comment] 2020-10-07 11:39
Inspired by this... #1385

**Comment by xsuchy** [comment] 2020-10-07 15:37
A good start is to start with the new stuff. It does not need to be perfectly organized. That can be the next step. But the goal is that search for `site:rpm.org %meta` will return something. And something else then just release notes. 
I believe that you may ask documentation team for help.

**Comment by pmatilai** [comment] 2020-10-08 03:46
Of course you gotta start with something, but even then you need to have some kind of framework to place things into, you can't just add a file/url named "meta" to explain said dependency attribute :sweat_smile: 
The beginnings of that framework is now laid into place so it'll be easier to add things, and having the "reference manual" in tree means we can also demand gets updated in pull-requests.

**Comment by pmatilai** [comment] 2021-01-15 13:12
There's now rudimentary docs of spec things, and more importantly, place to add more.
I'm closing this with an understanding that this is far from complete, but it also makes no sense for us to keep this ticket forever open.

Thanks for the initiative.

**Closed by pmatilai** 2021-01-15 13:12 UTC
