### ISSUE TITLE
librpm’s atexit() memory can free memory other threads are still using

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/rpm#1645] opened 2021-04-18 19:30 UTC
librpm installs an `atexit()` handler to clean up resources, but there is no protection against other threads that are still using those resources.  The result is undefined behavior.  According to [this comment by Rich Feckler](https://github.com/rust-lang/rust/issues/83994#issuecomment-820572419) (maintainer of musl libc) this is a bug in librpm.

**Comment by pmatilai** [comment] 2021-04-19 07:22
Sure it is. As we recently documented, rpm generally isn't generally anywhere near to being thread-safe.
With BDB gone, we could probably rip up a whole layer of signal related crud from rpm but it's pretty deeply woven...

**Comment by DemiMarie** [comment] 2021-04-19 14:19
> Sure it is. As we recently documented, rpm generally isn't generally anywhere near to being thread-safe.
> With BDB gone, we could probably rip up a whole layer of signal related crud from rpm but it's pretty deeply woven...

Fixing this long-term will require rpm to use a subprocess for `chroot()`, but for now we can just rip out the `atexit()` handler.  PR coming.

**Comment by pmatilai** [comment] 2022-03-23 07:53
atexit() is gone as of commit 35b93119a30029a889346a2b93312f031888524d, closing. 
So #1943 was basically a duplicate of this.

**Closed by pmatilai** 2022-03-23 07:53 UTC
